(function(g){var window=this;var $Da=function(a,b){return g.Wb(a,b)},b6=function(a){g.Fn(a,"zx",g.wc());
return a},c6=function(a,b,c){g.Fa(c)||(c=[String(c)]);
g.In(a.o,b,c)},aEa=function(a,b){var c=[];
g.tl(b,function(a){try{var b=g.gE.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.za(b)?g.fE(b)&&c.push(a):c.push(a)},a);
return c},bEa=function(a,b){var c=aEa(a,b);
(0,g.C)(c,function(a){g.gE.prototype.remove.call(this,a)},a)},cEa=function(a){if(a.Nd){if(a.Nd.locationOverrideToken)return{locationOverrideToken:a.Nd.locationOverrideToken};
if(null!=a.Nd.latitudeE7&&null!=a.Nd.longitudeE7)return{latitudeE7:a.Nd.latitudeE7,longitudeE7:a.Nd.longitudeE7}}return null},dEa=function(a,b,c,d){var e=new g.wn(null,void 0);
a&&g.xn(e,a);b&&g.yn(e,b);c&&g.zn(e,c);d&&g.An(e,d);return e},d6=function(a,b){g.ZE[a]=!0;
var c=g.XE();c&&c.publish.apply(c,arguments);g.ZE[a]=!1},e6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.qn;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",eEa(this,a.capabilities||""),fEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},eEa=function(a,b){a.capabilities.clear();
(0,g.oe)(b.split(","),g.La($Da,gEa)).forEach(function(b){a.capabilities.add(b)})},fEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},f6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},g6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},hEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},iEa=function(a){return new f6(a)},jEa=function(a){return g.Fa(a)?(0,g.I)(a,iEa):[]},h6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},i6=function(a){return g.Fa(a)?"["+(0,g.I)(a,h6).join(",")+"]":"null"},j6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},kEa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},k6=function(a,b){return g.Ra(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},l6=function(a,b){return g.Ra(a,function(a){return g6(a,b)})},lEa=function(){var a=(0,g.iI)();
a&&bEa(a,a.o.ce(!0))},m6=function(){var a=g.lI("yt-remote-connected-devices")||[];
g.qb(a);return a},mEa=function(a){if(g.Wa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},nEa=function(a){g.kI("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.lI("yt-remote-device-id");a||(a=j6(),g.kI("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.Va(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.Va(a,b);g.nI()&&g.sb(a,b);a=mEa(a);if(g.Wa(a))try{g.IH("remote_sid")}catch(c){}else try{g.HH("remote_sid",a.join(","),-1)}catch(c){}},oEa=function(){return g.lI("yt-remote-session-browser-channel")},pEa=function(){return g.lI("yt-remote-local-screens")||[]},qEa=function(){g.kI("yt-remote-lounge-token-expiration",!0,86400)},rEa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(pEa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.mj)(c,function(a){return!g.Va(b,a)})&&qEa();
g.kI("yt-remote-local-screens",a,31536E3)},sEa=function(a,b){g.kI("yt-remote-session-browser-channel",a);
g.kI("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.Va(c,d)||c.push(d);nEa(c);p6()},q6=function(a){a||(g.mI("yt-remote-session-screen-id"),g.mI("yt-remote-session-video-id"));
p6();a=m6();g.$a(a,o6());nEa(a)},tEa=function(){if(!r6){var a=g.rE();
a&&(r6=new g.aE(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},s6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},uEa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},t6=function(a){a.length?vEa(a.shift(),function(){t6(a)}):u6()},wEa=function(a){return"chrome-extension://"+a+v6},vEa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},u6=function(){var a=uEa();
a&&a(!1,"No cast extension found")},yEa=function(){if(xEa){var a=2,b=uEa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;vEa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",u6,c)}},zEa=function(){yEa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);t6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+v6,"//www.gstatic.com/eureka/clank"+v6])},w6=function(a,b,c){g.J.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Gd=b;this.D=(0,g.A)(this.dL,this);this.o=!1;this.A=0;this.B=this.Ia=null;this.C=[]},x6=function(){},y6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Mn(this);this.A=new g.Pg;this.A.setInterval(250)},BEa=function(a,b,c){a.bk=1;
a.Dh=b6(b.clone());a.nj=c;a.D=!0;AEa(a,null)},z6=function(a,b,c,d,e){a.bk=1;
a.Dh=b6(b.clone());a.nj=null;a.D=c;e&&(a.IF=!1);AEa(a,d)},AEa=function(a,b){a.Wk=(0,g.H)();
A6(a);a.fi=a.Dh.clone();c6(a.fi,"t",a.F);a.Xn=0;a.Vc=a.o.Rt(a.o.Pn()?b:null);0<a.zu&&(a.Xq=new g.bm((0,g.A)(a.YG,a,a.Vc),a.zu));a.Y.X(a.Vc,"readystatechange",a.jV);var c=a.Li?g.gc(a.Li):{};a.nj?(a.Xr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Vc.send(a.fi,a.Xr,a.nj,c)):(a.Xr="GET",a.IF&&!g.ce&&(c.Connection="close"),a.Vc.send(a.fi,a.Xr,null,c));a.o.Af(1)},EEa=function(a,b,c){for(var d=!0;!a.ti&&a.Xn<c.length;){var e=CEa(a,c);
if(e==B6){4==b&&(a.Eh=4,C6(15),d=!1);break}else if(e==DEa){a.Eh=4;C6(16);d=!1;break}else D6(a,e)}4==b&&0==c.length&&(a.Eh=1,C6(17),d=!1);a.Gf=a.Gf&&d;d||(E6(a),F6(a))},CEa=function(a,b){var c=a.Xn,d=b.indexOf("\n",c);
if(-1==d)return B6;c=Number(b.substring(c,d));if(isNaN(c))return DEa;d+=1;if(d+c>b.length)return B6;var e=b.substr(d,c);a.Xn=d+c;return e},GEa=function(a,b){a.Wk=(0,g.H)();
A6(a);var c=b?window.location.hostname:"";a.fi=a.Dh.clone();g.Fn(a.fi,"DOMAIN",c);g.Fn(a.fi,"t",a.F);try{a.If=new ActiveXObject("htmlfile")}catch(n){E6(a);a.Eh=7;C6(22);F6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in G6)k=G6[l];else if(l in FEa)k=G6[l]=FEa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
G6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Fd(g.Tc("b/12014412"),d+"</body></html>");a.If.open();a.If.write(g.td(c));a.If.close();a.If.parentWindow.m=(0,g.A)(a.pU,a);a.If.parentWindow.d=(0,g.A)(a.TE,a,!0);a.If.parentWindow.rpcClose=(0,g.A)(a.TE,a,!1);c=a.If.createElement("DIV");a.If.parentWindow.document.body.appendChild(c);d=g.gd(a.fi.toString());d=g.rc(g.dd(d));d=g.Fd(g.Tc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Bd(c,g.td(d));a.o.Af(1)},A6=function(a){a.oy=(0,g.H)()+
a.C;
HEa(a,a.C)},HEa=function(a,b){if(null!=a.zl)throw Error("WatchDog timer not null");
a.zl=H6((0,g.A)(a.EU,a),b)},I6=function(a){a.zl&&(g.v.clearTimeout(a.zl),a.zl=null)},F6=function(a){a.o.EB()||a.ti||a.o.Fq(a)},E6=function(a){I6(a);
g.Bf(a.Xq);a.Xq=null;a.A.stop();g.Sn(a.Y);if(a.Vc){var b=a.Vc;a.Vc=null;b.abort();b.dispose()}a.If&&(a.If=null)},D6=function(a,b){try{a.o.ME(a,b),a.o.Af(4)}catch(c){}},JEa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;IEa(a,b,function(e){e?c(!0):g.v.setTimeout(function(){JEa(a,b,c,d,f)},f)})}},IEa=function(a,b,c){var d=new Image;
d.onload=function(){try{J6(d),c(!0)}catch(e){}};
d.onerror=function(){try{J6(d),c(!1)}catch(e){}};
d.onabort=function(){try{J6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{J6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},J6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},KEa=function(a){this.o=a;
this.A=new x6},LEa=function(a){var b=K6(a.o,a.Pl,"/mail/images/cleardot.gif");
b6(b);JEa(b.toString(),5E3,(0,g.A)(a.eK,a),3,2E3);a.Af(1)},M6=function(a){var b=a.o.J;
if(null!=b)C6(5),b?(C6(11),L6(a.o,a,!1)):(C6(12),L6(a.o,a,!0));else if(a.Ee=new y6(a,void 0,void 0,void 0),a.Ee.Li=a.xu,b=a.o,b=K6(b,b.Pn()?a.Gm:null,a.yu),C6(5),!g.ae||g.Lc(10))c6(b,"TYPE","xmlhttp"),z6(a.Ee,b,!1,a.Gm,!1);else{c6(b,"TYPE","html");var c=a.Ee;a=!!a.Gm;c.bk=3;c.Dh=b6(b.clone());GEa(c,a)}},N6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new x6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},MEa=function(a,b){this.o=a;
this.map=b;this.context=null},NEa=function(a){g.Df.call(this,"statevent",a)},OEa=function(a,b){g.Df.call(this,"timingevent",a);
this.size=b},PEa=function(a){g.Df.call(this,"serverreachability",a)},SEa=function(a){QEa(a);
if(3==a.o){var b=a.xn++,c=a.hp.clone();g.Fn(c,"SID",a.B);g.Fn(c,"RID",b);g.Fn(c,"TYPE","terminate");O6(a,c);b=new y6(a,a.B,b,void 0);b.bk=2;b.Dh=b6(c.clone());(new Image).src=b.Dh;b.Wk=(0,g.H)();A6(b)}REa(a)},TEa=function(a){a.BK(1,0);
a.hp=K6(a,null,a.wu);P6(a)},QEa=function(a){a.rh&&(a.rh.abort(),a.rh=null);
a.Ac&&(a.Ac.cancel(),a.Ac=null);a.Gg&&(g.v.clearTimeout(a.Gg),a.Gg=null);Q6(a);a.ie&&(a.ie.cancel(),a.ie=null);a.xh&&(g.v.clearTimeout(a.xh),a.xh=null)},UEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new MEa(a.cQ++,b));2!=a.o&&3!=a.o||P6(a)},P6=function(a){a.ie||a.xh||(a.xh=H6((0,g.A)(a.SE,a),0),a.Sj=0)},WEa=function(a,b){if(1==a.o){if(!b){a.xn=Math.floor(1E5*Math.random());
var c=a.xn++,d=new y6(a,"",c,void 0);d.Li=null;var e=R6(a),f=a.hp.clone();g.Fn(f,"RID",c);g.Fn(f,"CVER","1");O6(a,f);BEa(d,f,e);a.ie=d;a.o=2}}else 3==a.o&&(b?VEa(a,b):0==a.A.length||a.ie||VEa(a))},VEa=function(a,b){if(b)if(6<a.yi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.xn-1;var d=R6(a)}else c=b.G,d=b.nj;else c=a.xn++,d=R6(a);var e=a.hp.clone();g.Fn(e,"SID",a.B);g.Fn(e,"RID",c);g.Fn(e,"AID",a.wk);O6(a,e);c=new y6(a,a.B,c,a.Sj+1);c.Li=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ie=c;BEa(c,e,d)},O6=function(a,b){if(a.Fd){var c=a.Fd.jB();
c&&g.Kb(c,function(a,c){g.Fn(b,c,a)})}},R6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.yi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.yi?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+encodeURIComponent(a))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},XEa=function(a){a.Ac||a.Gg||(a.G=1,a.Gg=H6((0,g.A)(a.RE,a),0),a.Jj=0)},S6=function(a){if(a.Ac||a.Gg||3<=a.Jj)return!1;
a.G++;a.Gg=H6((0,g.A)(a.RE,a),YEa(a,a.Jj));a.Jj++;return!0},L6=function(a,b,c){a.Ur=c;
a.Vf=b.Tg;a.F||TEa(a)},Q6=function(a){null!=a.Ai&&(g.v.clearTimeout(a.Ai),a.Ai=null)},YEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},T6=function(a,b){if(2==b||9==b){var c=null;
a.Fd&&(c=null);var d=(0,g.A)(a.cW,a);c||(c=new g.wn("//www.google.com/images/cleardot.gif"),b6(c));IEa(c.toString(),1E4,d)}else C6(2);ZEa(a,b)},ZEa=function(a,b){a.o=0;
a.Fd&&a.Fd.hA(b);REa(a);QEa(a)},REa=function(a){a.o=0;
a.Vf=-1;if(a.Fd)if(0==a.C.length&&0==a.A.length)a.Fd.Dt();else{g.db(a.C);var b=g.db(a.A);a.C.length=0;a.A.length=0;a.Fd.Dt(b)}},K6=function(a,b,c){var d=g.Gn(c);
if(""!=d.A)b&&g.yn(d,b+"."+d.A),g.zn(d,d.D);else{var e=window.location;d=dEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.im&&g.Kb(a.im,function(a,b){g.Fn(d,b,a)});
g.Fn(d,"VER",a.yi);O6(a,d);return d},H6=function(a,b){if(!g.Ha(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},C6=function(a){U6.dispatchEvent(new NEa(U6,a))},$Ea=function(){},aFa=function(a,b){this.action=a;
this.params=b||{}},V6=function(a,b){g.J.call(this);
this.o=new g.U(this.fU,0,this);g.K(this,this.o);this.Gd=5E3;this.A=0;if(g.Ha(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ha(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},W6=function(a,b,c){this.K=a;
this.F=b;this.B=new g.$D;this.A=new V6(this.GW,this);this.o=this.kb=null;this.Cb=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.L=c||!1},bFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Ur,sessionId:a.o.B,arrayId:a.o.wk}},cFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&WEa(a.o),SEa(a.o));a.H=0},X6=function(a){return!!a.o&&3==a.o.o},dFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Y6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.dh(a)||"";b&&(this.port=":"+b);this.domain=g.ch(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.A=!1))},Z6=function(a,b){var c=a.o;
if(g.za(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.mh(c+b,{})},$6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.La(a.C,d,!0),onError:g.La(a.B,e),Kd:g.La(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.FF(b,a)},hFa=function(){var a=eFa;
fFa();a7.push(a);gFa(a7)},b7=function(a,b){fFa();
var c=a7,d=iFa(a,String(b));g.Wa(c)?jFa(d):(gFa(c),(0,g.C)(c,function(a){a(d)}))},fFa=function(){a7||(a7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ca("yt.mdx.remote.debug.handlers_",a7,void 0))},jFa=function(a){var b=(c7+1)%50;
c7=b;d7[b]=a;e7||(e7=49==b)},gFa=function(a){var b=d7;
if(b[0]){var c=c7,d=e7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
d7=Array(50);c7=-1;e7=!1}},iFa=function(a,b){var c=((0,g.H)()-kFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},f7=function(a){g.V.call(this);
this.G=a;this.o=[]},lFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},mFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.oe)(a.o,function(a){return!!k6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=lFa(a,b[d])||c;return c},nFa=function(a,b){var c=a.o.length;
a.o=(0,g.oe)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},g7=function(a,b,c,d){g.V.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ia=NaN},i7=function(a){f7.call(this,"LocalScreenService");
this.B=a;this.A=NaN;h7(this);this.info("Initializing with "+i6(this.o))},oFa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=Z6(a.B,"/pairing/get_lounge_token_batch");
$6(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.rL,a),(0,g.A)(a.qL,a))}},h7=function(a){var b=jEa(pEa());
b=(0,g.oe)(b,function(a){return!a.uuid});
return mFa(a,b)},j7=function(a,b){rEa((0,g.I)(a.o,hEa));
b&&qEa()},l7=function(a,b){g.V.call(this);
this.F=b;var c=g.lI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Va(c,l)}this.o=d;this.D=a;this.B=this.C=NaN;this.A=null;k7("Initialized with "+g.Vg(this.o))},pFa=function(a,b,c){var d=Z6(a.D,"/pairing/get_screen_availability");
$6(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},m7=function(a,b){a:if(g.Qb(b)!=g.Qb(a.o))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(k7("Updated online screens: "+g.Vg(a.o)),a.o=b,a.V("screenChange"));qFa(a)},n7=function(a){isNaN(a.B)||g.WE(a.B);
a.B=g.UE((0,g.A)(a.jx,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},k7=function(a){b7("OnlineScreenService",a)},rFa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.uc("Requesting availability of screen w/o lounge token.")});
return b},qFa=function(a){a=g.Tb(g.Lb(a.o,function(a){return a}));
g.qb(a);a.length?g.kI("yt-remote-online-screen-ids",a.join(","),60):g.mI("yt-remote-online-screen-ids")},o7=function(a){f7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};sFa(this)},uFa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ye();if(k=(c?l6(k,c):null)||l6(k,b)){k.uuid=b;var l=p7(a,k);pFa(a.A,l,function(a){e(a?l:null)})}else c?tFa(a,c,(0,g.A)(function(a){var f=p7(this,new f6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));pFa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},vFa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},tFa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.FF(Z6(a.F,"/pairing/get_lounge_token_batch"),e)},wFa=function(a){a.o=a.B.ye();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+i6(a.o))},sFa=function(a){q7(a);
a.B=new i7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.FL,a));wFa(a);a.C=jEa(g.lI("yt-remote-automatic-screen-cache")||[]);q7(a);a.info("Initializing automatic screens: "+i6(a.C));a.A=new l7(a.F,(0,g.A)(a.ye,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},p7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=l6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.kI("yt-remote-automatic-screen-cache",(0,g.I)(a.C,hEa)));q7(a);a.D[b.uuid]=b.id;g.kI("yt-remote-device-id-map",a.D,31536E3);return b},q7=function(a){a.D=g.lI("yt-remote-device-id-map")||{}},r7=function(a,b,c){g.V.call(this);
this.R=c;this.J=a;this.A=b;this.B=null},s7=function(a,b){b7(a.R,b)},t7=function(a,b){r7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.MW,this);this.D=(0,g.A)(this.QU,this);this.C=g.UE((0,g.A)(function(){xFa(this,null)},this),12E4)},yFa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Vg(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){s7(this,"Failed to send message: getMdxSessionStatus.")},a)):s7(a,"Sending yt message without session: "+g.Vg(b))},xFa=function(a,b){g.WE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Gq,a),d=(0,g.A)(a.De,a);a.uB(b,c,d,5)}}else a.De(Error("Waiting for session status timed out."))},u7=function(a,b,c){r7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.N=c;this.D=null;this.G=g.z;this.F=NaN;this.L=(0,g.A)(this.PW,this);this.o=g.z},zFa=function(a){a.o=a.J.cH(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.Gq(a)},a),(0,g.A)(function(a){this.o=g.z;
this.De(a)},a))},AFa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.N;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}tEa()&&(b.env_useStageMdx=1);return g.kh(b)},v7=function(a,b){r7.call(this,a,b,"ManualSession");
this.o=g.UE((0,g.A)(this.yk,this,null),150)},w7=function(a,b,c,d){g.V.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.oT,this)},BFa=function(a,b){return b?g.Ra(a.B,function(a){return g6(b,a.label)},a):null},x7=function(a){b7("Controller",a)},eFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},y7=function(a){return a.D||!!a.B.length||!!a.o},z7=function(a,b,c){b!=a.o&&(g.Bf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.PE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.yk(null)):a.V("yt-remote-cast2-session-change",null))},CFa=function(a){var b=a.A.bH(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&g6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=BFa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new chrome.cast.Receiver(b,a.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},IFa=function(a,b,c,d,e,f,k){DFa()?EFa(b,e,f,k)&&(B7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?FFa(a,c):(window.__onGCastApiAvailable=function(b,d){b?FFa(a,c):(C7("Failed to load cast API: "+d),D7(!1),B7(!1),g.mI("yt-remote-cast-available"),g.mI("yt-remote-cast-receiver"),GFa(),c(!1))},d?g.gF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?zEa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?u6():(yEa(),t6(HFa.map(wEa))))):A7("Cannot initialize because not running Chrome")},GFa=function(){A7("dispose");
var a=E7();a&&a.dispose();g.Ca("yt.mdx.remote.cloudview.instance_",null,void 0);JFa(!1);g.bF(F7);F7.length=0},G7=function(){return!!g.lI("yt-remote-cast-installed")},KFa=function(){var a=g.lI("yt-remote-cast-receiver");
return a?a.friendlyName:null},LFa=function(){A7("clearCurrentReceiver");
g.mI("yt-remote-cast-receiver")},MFa=function(){return G7()?E7()?E7().getCastSession():(C7("getCastSelector: Cast is not initialized."),null):(C7("getCastSelector: Cast API is not installed!"),null)},I7=function(){G7()?E7()?H7()?(A7("Requesting cast selector."),E7().requestSession()):(A7("Wait for cast API to be ready to request the session."),F7.push(g.aF("yt-remote-cast2-api-ready",I7))):C7("requestCastSelector: Cast is not initialized."):C7("requestCastSelector: Cast API is not installed!")},J7=
function(a,b){H7()?E7().setConnectedScreenStatus(a,b):C7("setConnectedScreenStatus called before ready.")},DFa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.JL||a},NFa=function(a,b){E7().init(a,b)},EFa=function(a,b,c,d){var e=!1;
E7()||(a=new w7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.kI("yt-remote-cast-available",a);d6("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){A7("onReceiverSelected: "+a.friendlyName);
g.kI("yt-remote-cast-receiver",a);d6("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){A7("onReceiverResumed: "+a.friendlyName);
g.kI("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){A7("onSessionChange: "+h6(a));
a||g.mI("yt-remote-cast-receiver");d6("yt-remote-cast2-session-change",a)}),g.Ca("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
A7("cloudview.createSingleton_: "+e);return e},E7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},FFa=function(a,b){D7(!0);
B7(!1);NFa(a,function(a){a?(JFa(!0),g.dF("yt-remote-cast2-api-ready")):(C7("Failed to initialize cast API."),D7(!1),g.mI("yt-remote-cast-available"),g.mI("yt-remote-cast-receiver"),GFa());b(a)})},A7=function(a){b7("cloudview",a)},C7=function(a){b7("cloudview",a)},D7=function(a){A7("setCastInstalled_ "+a);
g.kI("yt-remote-cast-installed",a)},H7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},JFa=function(a){A7("setApiReady_ "+a);
g.Ca("yt.mdx.remote.cloudview.apiReady_",a,void 0)},B7=function(a){g.Ca("yt.mdx.remote.cloudview.initializing_",a,void 0)},K7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.D=0;this.o=null;this.hasNext=this.Zf=!1;this.J=this.G=this.F=this.B=0;this.A=NaN;this.H=!1;this.reset(a)},L7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Zf=!1;a.hasNext=!1;a.D=0;a.C=(0,g.H)();a.B=0;a.F=0;a.G=0;a.J=0;a.A=NaN;a.H=!1},M7=function(a){return a.tb()?((0,g.H)()-a.C)/1E3:0},N7=function(a,b){a.D=b;
a.C=(0,g.H)()},O7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.C)/1E3+a.D;
case -1E3:return 0}return a.D},P7=function(a){return a.H?a.F+M7(a):a.F},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&L7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.hc(a.o);b.hasPrevious=a.Zf;b.hasNext=a.hasNext;b.playerTime=a.D;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.F;b.duration=a.G;b.loadedTime=a.J;b.liveIngestionTime=a.A;return b},T7=function(a,b){g.V.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.qD;this.B=this.A=null;this.J=(0,g.A)(this.NQ,this);this.G=(0,g.A)(this.An,this);this.H=(0,g.A)(this.MQ,this);this.K=(0,g.A)(this.ZQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.zy,this),OFa(this))):c=3;0!=c&&(b?this.zy(c):g.UE((0,g.A)(function(){this.zy(c)},this),0));
var d=MFa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new K7(a.C.getPlayerContextData())},OFa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.La(this.jT,a),this))},a)},PFa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},V7=function(a,b){50>a.D.Kc()&&g.sD(a.D,b)},X7=function(a,b,c){var d=U7(a);
N7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){PFa(a);
a.C.setPlayerContextData(R7(b));OFa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.An(null));
a.B=b;a.B&&(b7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.An(a.B.media[0]))},QFa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&b7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;N7(d,a.A.getEstimatedTime());W7(a,d)}else b7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(a){this.uc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.uc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.V.call(this);
this.D=NaN;this.N=!1;this.K=this.J=this.L=this.R=NaN;this.T=[];this.C=this.G=this.B=this.qb=this.o=null;this.sa=a;this.T.push(g.HG(window,"beforeunload",(0,g.A)(this.hL,this)));this.A=[];this.qb=new K7;this.aa=b.id;this.o=RFa(this,c);this.o.subscribe("handlerOpened",this.RQ,this);this.o.subscribe("handlerClosed",this.OQ,this);this.o.subscribe("handlerError",this.PQ,this);this.o.subscribe("handlerMessage",this.QQ,this);dFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=this.qb.videoId;
g.nI()&&g.kI("yt-remote-session-video-id",a)},this)},a8=function(a){b7("conn",a)},RFa=function(a,b){return new W6(Z6(a.sa,"/bc"),b)},b8=function(a,b){a.V("proxyStateChange",b)},SFa=function(a){a.D=g.UE((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.WE(a.D);
a.D=NaN},d8=function(a){g.WE(a.R);
a.R=NaN},TFa=function(a){e8(a);
a.L=g.UE((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.WE(a.L);
a.L=NaN},VFa=function(a,b){b&&(c8(a),d8(a));
b==(X6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),UFa(a)):a.F(1)},WFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.bc(b.params)?a.qb.o=null:a.qb.o=b.params,a.V("remotePlayerChange"))},XFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.V("remoteQueueChange")},ZFa=function(a,b){b.params=b.params||{};
XFa(a,b);YFa(a,b);a.V("autoplayDismissed")},YFa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
N7(a.qb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=isNaN(c)?0:c;c=Number(b.params.duration);a.qb.G=isNaN(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.A=d;c.H=isNaN(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.F=isNaN(e)?0:e;1==a.qb.playerState?TFa(a):e8(a);a.V("remotePlayerChange")},$Fa=function(a,b){if(-1E3!=
a.qb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=parseInt(b.params.currentTime,10);N7(a.qb,isNaN(c)?0:c);a.V("remotePlayerChange")}},aGa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=parseInt(b.params.volume,10);a.qb.muted=c;a.V("remotePlayerChange")},bGa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},cGa=function(a,b){var c="true"==b.params.hasNext;
a.qb.Zf="true"==b.params.hasPrevious;a.qb.hasNext=c;a.V("previousNextChange")},UFa=function(a){g.WE(a.K);
a.K=g.UE((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.Vg(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){f7.call(this,"ScreenServiceProxy");
this.ld=a;this.A=[];this.A.push(this.ld.$_s("screenChange",(0,g.A)(this.KW,this)));this.A.push(this.ld.$_s("onlineScreenChange",(0,g.A)(this.IS,this)))},hGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ME("MDX_CONFIG")||b;lEa();p6();h8||(h8=new Y6(b?b.loungeApiHost:void 0),tEa()&&(h8.o="/api/loungedev"));i8||(i8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ca("yt.mdx.remote.deferredProxies_",i8,void 0));dGa();var c=j8();if(!c){var d=new o7(h8);g.Ca("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);IFa(a,d,function(a){a?k8()&&J7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){d6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ca("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.Vg(b)),m8.push(g.aF("yt-remote-cast2-availability-change",function(){d6("yt-remote-receiver-availability-change")})),m8.push(g.aF("yt-remote-cast2-receiver-selected",function(){n8(null);
d6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.aF("yt-remote-cast2-receiver-resumed",function(){d6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.aF("yt-remote-cast2-session-change",eGa)),m8.push(g.aF("yt-remote-connection-change",function(a){a?J7(k8(),"YouTube TV"):o8()||(J7(null,null),LFa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.oF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.Vg(a)),fGa(a),c.start(),k8()||gGa())},jGa=function(){var a=iGa();
G7()&&g.lI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},iGa=function(){var a=j8().ld.$_gos();
var b=q8();b&&r8()&&(k6(a,b)||a.push(b));return kEa(a)},s8=function(){var a=kGa();
!a&&G7()&&KFa()&&(a={key:"cast-selector-receiver",name:KFa()});return a},kGa=function(){var a=iGa(),b=q8();
b||(b=o8());return g.Ra(a,function(a){return b&&g6(b,a.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().ye();return l6(b,a)},eGa=function(a){l8("remote.onCastSessionChange_: "+h6(a));
if(a){var b=q8();b&&b.id==a.id?J7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){H7()?E7().stopSession():C7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){b7("remote",a)},j8=function(){if(!x8){var a=g.w("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.w("yt.mdx.remote.currentScreenId_")},lGa=function(a){g.Ca("yt.mdx.remote.currentScreenId_",a,void 0)},mGa=function(){return g.w("yt.mdx.remote.connectData_")},n8=function(a){g.Ca("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.w("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||lGa("");g.Ca("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(b){b(a)}),i8.length=0);
b&&!a?d6("yt-remote-connection-change",!1):!b&&a&&d6("yt-remote-connection-change",!0)},o8=function(){var a=g.nI();
if(!a)return null;var b=j8().ye();return l6(b,a)},u8=function(a,b){q8()&&q8();
lGa(a.id);var c=new $7(h8,a,p8());c.connect(b,mGa());c.subscribe("beforeDisconnect",function(a){d6("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},gGa=function(){var a=o8();
a?(l8("Resume connection to: "+h6(a)),u8(a,0)):(q6(),LFa(),l8("Skipping connecting because no session screen found."))},dGa=function(){var a=p8();
if(g.bc(a)){a=o6();var b=g.lI("yt-remote-session-name")||"",c=g.lI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ca("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},fGa=function(a){a?(g.kI("yt-remote-session-app",a.app),g.kI("yt-remote-session-name",a.name)):(g.mI("yt-remote-session-app"),g.mI("yt-remote-session-name"));
g.Ca("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.J.call(this);
this.D=a;this.A=b;this.B=new g.WG(this);g.K(this,this.B);this.B.O(b,"onCaptionsTrackListChanged",this.cS);this.B.O(b,"captionschanged",this.LQ);this.B.O(b,"captionssettingschanged",this.oG);this.B.O(b,"videoplayerreset",this.Hq);this.B.O(b,"mdxautoplaycancel",this.dK);this.T=this.B.O(b,"onVolumeChange",this.wE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.LE,this);c.subscribe("remotePlayerChange",this.Dn,this);c.subscribe("remoteQueueChange",this.Hq,this);c.subscribe("autoplayUpNext",this.iE,
this);c.subscribe("previousNextChange",this.IE,this);c.subscribe("nowAutoplaying",this.AE,this);c.subscribe("autoplayDismissed",this.hE,this);this.suggestion=null;this.J=new g.MQ(64);this.C=new g.U(this.lG,500,this);g.K(this,this.C);this.F=new g.U(this.mG,1E3,this);g.K(this,this.F);this.L=new w6(this.mW,0,this);g.K(this,this.L);this.G={};this.R=new g.U(this.OG,1E3,this);g.K(this,this.R);this.K=new g.bm(this.FO,1E3,this);g.K(this,this.K);this.N=g.z;this.oG();this.Hq();this.Dn()},z8=function(a,b){a.D.Ie(b,
a.A.getVideoData().lengthSeconds)},nGa=function(a){z8(a,0);
a.C.stop();A8(a,new g.MQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.jc(c,b));a.o.ZF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.xe();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.mk,cEa(c));A8(a,new g.MQ(1))},oGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{M4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.SQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.UU(a.A,d);a.J=b;pGa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",P:[{I:"div",M:"ytp-remote-display-status",P:[{I:"div",M:"ytp-remote-display-status-icon",P:[g.Esa()]},{I:"div",M:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.B=new g.LV(this,250);g.K(this,this.B);this.C=a;this.O(a,"presentingplayerstatechange",this.D);qGa(this,g.QU(a))},qGa=function(a,b){if(3==a.C.getPresentingPlayerType()){var c={RECEIVER_NAME:a.C.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.DV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.DV("Playing on $RECEIVER_NAME",c):g.DV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.bX.call(this,"Play on",0,a,b);
this.B=a;this.H={};this.O(a,"onMdxReceiversChange",this.L);this.O(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.nV.call(this,a);
this.A={key:j6(),name:"This computer"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.ln=new g.MQ(64);this.J=0;this.H=-1;if(!g.IN(g.Y(this.player))){a=this.player;var b=g.BQ(a);b&&(b=b.nn())&&(b=new F8(a,b),g.K(this,b));b=new E8(a);g.K(this,b);g.eV(a,b.element,4)}},pGa=function(a,b,c){a.ln=c;
a.player.V("presentingplayerstatechange",new g.WQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ga(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.mk,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=cEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.Vg(b));"cast-selector-receiver"==b.key?
(n8(d||null),H7()?E7().setLaunchParams(d||null):C7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?d6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().ye(),(d=l6(d,b.key))&&u8(d,1))}},FEa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},G6={"'":"\\'"},rGa={},gEa={iY:"atp",O2:"ska",c2:"que",m1:"mus",K2:"sus",v_:"dsp",u2:"seq"};
e6.prototype.sh=function(){var a=new e6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var r6,n6="",v6=s6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",xEa=s6("loadCastFramework")||s6("loadCastApplicationFramework"),HFa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(w6,g.J);g.h=w6.prototype;g.h.cL=function(a){this.C=arguments;this.o=!1;this.Ia?this.B=(0,g.H)()+this.Gd:this.Ia=g.Qg(this.D,this.Gd)};
g.h.stop=function(){this.Ia&&(g.Rg(this.Ia),this.Ia=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.W=function(){this.stop();w6.ga.W.call(this)};
g.h.dL=function(){this.B?(this.Ia=g.Qg(this.D,this.B-(0,g.H)()),this.B=null):(this.Ia=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};x6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
x6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=y6.prototype;g.h.Li=null;g.h.Gf=!1;g.h.zl=null;g.h.oy=null;g.h.Wk=null;g.h.bk=null;g.h.Dh=null;g.h.fi=null;g.h.nj=null;g.h.Vc=null;g.h.Xn=0;g.h.If=null;g.h.Xr=null;g.h.Eh=null;g.h.Hm=-1;g.h.IF=!0;g.h.ti=!1;g.h.zu=0;g.h.Xq=null;var DEa={},B6={};g.h=y6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.jV=function(a){a=a.target;var b=this.Xq;b&&3==g.ly(a)?b.Dm():this.YG(a)};
g.h.YG=function(a){try{if(a==this.Vc)a:{var b=g.ly(this.Vc),c=this.Vc.A,d=this.Vc.getStatus();if(g.ae&&!g.Lc(10)||g.ce&&!g.Kc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ff&&!g.py(this.Vc))break a;this.ti||4!=b||7==c||(8==c||0>=d?this.o.Af(3):this.o.Af(2));I6(this);var e=this.Vc.getStatus();this.Hm=e;var f=g.py(this.Vc);(this.Gf=200==e)?(4==b&&E6(this),this.D?(EEa(this,b,f),g.Ff&&this.Gf&&3==b&&(this.Y.X(this.A,"tick",this.eV),this.A.start())):D6(this,f),this.Gf&&!this.ti&&(4==b?this.o.Fq(this):
(this.Gf=!1,A6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Eh=3,C6(13)):(this.Eh=0,C6(14)),E6(this),F6(this))}}catch(k){this.Vc&&g.py(this.Vc)}finally{}};
g.h.eV=function(){var a=g.ly(this.Vc),b=g.py(this.Vc);this.Xn<b.length&&(I6(this),EEa(this,a,b),this.Gf&&4!=a&&A6(this))};
g.h.pU=function(a){H6((0,g.A)(this.oU,this,a),0)};
g.h.oU=function(a){this.ti||(I6(this),D6(this,a),A6(this))};
g.h.TE=function(a){H6((0,g.A)(this.nU,this,a),0)};
g.h.nU=function(a){this.ti||(E6(this),this.Gf=a,this.o.Fq(this),this.o.Af(4))};
g.h.cancel=function(){this.ti=!0;E6(this)};
g.h.EU=function(){this.zl=null;var a=(0,g.H)();0<=a-this.oy?(2!=this.bk&&this.o.Af(3),E6(this),this.Eh=2,C6(18),F6(this)):HEa(this,this.oy-a)};
g.h.getLastError=function(){return this.Eh};g.h=KEa.prototype;g.h.xu=null;g.h.Ee=null;g.h.Yq=!1;g.h.FB=null;g.h.fp=null;g.h.Dv=null;g.h.yu=null;g.h.Ye=null;g.h.Tg=-1;g.h.Gm=null;g.h.Pl=null;g.h.connect=function(a){this.yu=a;a=K6(this.o,null,this.yu);C6(3);this.FB=(0,g.H)();var b=this.o.H;null!=b?(this.Gm=b[0],(this.Pl=b[1])?(this.Ye=1,LEa(this)):(this.Ye=2,M6(this))):(c6(a,"MODE","init"),this.Ee=new y6(this,void 0,void 0,void 0),this.Ee.Li=this.xu,z6(this.Ee,a,!1,null,!0),this.Ye=0)};
g.h.eK=function(a){if(a)this.Ye=2,M6(this);else{C6(4);var b=this.o;b.Vf=b.rh.Tg;T6(b,9)}a&&this.Af(2)};
g.h.Rt=function(a){return this.o.Rt(a)};
g.h.abort=function(){this.Ee&&(this.Ee.cancel(),this.Ee=null);this.Tg=-1};
g.h.EB=function(){return!1};
g.h.ME=function(a,b){this.Tg=a.Hm;if(0==this.Ye)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Vf=this.Tg;T6(c,2);return}this.Gm=c[0];this.Pl=c[1]}else c=this.o,c.Vf=this.Tg,T6(c,2);else if(2==this.Ye)if(this.Yq)C6(7),this.Dv=(0,g.H)();else if("11111"==b){if(C6(6),this.Yq=!0,this.fp=(0,g.H)(),c=this.fp-this.FB,!g.ae||g.Lc(10)||500>c)this.Tg=200,this.Ee.cancel(),C6(12),L6(this.o,this,!0)}else C6(8),this.fp=this.Dv=(0,g.H)(),this.Yq=!1};
g.h.Fq=function(){this.Tg=this.Ee.Hm;if(this.Ee.Gf)0==this.Ye?this.Pl?(this.Ye=1,LEa(this)):(this.Ye=2,M6(this)):2==this.Ye&&((!g.ae||g.Lc(10)?!this.Yq:200>this.Dv-this.fp)?(C6(11),L6(this.o,this,!1)):(C6(12),L6(this.o,this,!0)));else{0==this.Ye?C6(9):2==this.Ye&&C6(10);var a=this.o;a.Vf=this.Tg;T6(a,2)}};
g.h.Pn=function(){return this.o.Pn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Af=function(a){this.o.Af(a)};g.h=N6.prototype;g.h.im=null;g.h.ie=null;g.h.Ac=null;g.h.wu=null;g.h.hp=null;g.h.Wz=null;g.h.yp=null;g.h.xn=0;g.h.cQ=0;g.h.Fd=null;g.h.xh=null;g.h.Gg=null;g.h.Ai=null;g.h.rh=null;g.h.Ur=null;g.h.wk=-1;g.h.wC=-1;g.h.Vf=-1;g.h.Sj=0;g.h.Jj=0;g.h.yi=8;var U6=new g.eg;g.B(NEa,g.Df);g.B(OEa,g.Df);g.B(PEa,g.Df);g.h=N6.prototype;g.h.connect=function(a,b,c,d,e){C6(0);this.wu=b;this.im=c||{};d&&g.za(e)&&(this.im.OSID=d,this.im.OAID=e);this.F?(H6((0,g.A)(this.pA,this,a),100),TEa(this)):this.pA(a)};
g.h.pA=function(a){this.rh=new KEa(this);this.rh.xu=null;this.rh.A=this.D;this.rh.connect(a)};
g.h.EB=function(){return 0==this.o};
g.h.SE=function(a){this.xh=null;WEa(this,a)};
g.h.RE=function(){this.Gg=null;this.Ac=new y6(this,this.B,"rpc",this.G);this.Ac.Li=null;this.Ac.zu=0;var a=this.Wz.clone();g.Fn(a,"RID","rpc");g.Fn(a,"SID",this.B);g.Fn(a,"CI",this.Ur?"0":"1");g.Fn(a,"AID",this.wk);O6(this,a);if(!g.ae||g.Lc(10))g.Fn(a,"TYPE","xmlhttp"),z6(this.Ac,a,!0,this.yp,!1);else{g.Fn(a,"TYPE","html");var b=this.Ac,c=!!this.yp;b.bk=3;b.Dh=b6(a.clone());GEa(b,c)}};
g.h.ME=function(a,b){if(0!=this.o&&(this.Ac==a||this.ie==a))if(this.Vf=a.Hm,this.ie==a&&3==this.o)if(7<this.yi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Fa(c)&&3==c.length)if(0==c[0])a:{if(!this.Gg){if(this.Ac)if(this.Ac.Wk+3E3<this.ie.Wk)Q6(this),this.Ac.cancel(),this.Ac=null;else break a;S6(this);C6(19)}}else this.wC=c[1],0<this.wC-this.wk&&37500>c[2]&&this.Ur&&0==this.Jj&&!this.Ai&&(this.Ai=H6((0,g.A)(this.GQ,this),6E3));else T6(this,11)}else b!=rGa.mZ.o&&T6(this,11);else if(this.Ac==a&&
Q6(this),!g.D(b)){c=this.D.parse(b);g.Fa(c);for(var d=0;d<c.length;d++){var e=c[d];this.wk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.yp=e[2],e=e[3],null!=e?this.yi=e:this.yi=6,this.o=3,this.Fd&&this.Fd.jA(),this.Wz=K6(this,this.Pn()?this.yp:null,this.wu),XEa(this)):"stop"==e[0]&&T6(this,7):3==this.o&&("stop"==e[0]?T6(this,7):"noop"!=e[0]&&this.Fd&&this.Fd.iA(e),this.Jj=0)}}};
g.h.GQ=function(){null!=this.Ai&&(this.Ai=null,this.Ac.cancel(),this.Ac=null,S6(this),C6(20))};
g.h.Fq=function(a){if(this.Ac==a){Q6(this);this.Ac=null;var b=2}else if(this.ie==a)this.ie=null,b=1;else return;this.Vf=a.Hm;if(0!=this.o)if(a.Gf)1==b?(b=(0,g.H)()-a.Wk,U6.dispatchEvent(new OEa(U6,a.nj?a.nj.length:0,b,this.Sj)),P6(this),this.C.length=0):XEa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Vf)){if(d=1==b)this.ie||this.xh||1==this.o||2<=this.Sj?d=!1:(this.xh=H6((0,g.A)(this.SE,this,a),YEa(this,this.Sj)),this.Sj++,d=!0);d=!(d||2==b&&S6(this))}if(d)switch(c){case 1:T6(this,
5);break;case 4:T6(this,10);break;case 3:T6(this,6);break;case 7:T6(this,12);break;default:T6(this,2)}}};
g.h.BK=function(a){if(!g.Va(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.cW=function(a){a?C6(2):(C6(1),ZEa(this,8))};
g.h.Rt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.fy;a.H=!1;return a};
g.h.isActive=function(){return!!this.Fd&&this.Fd.isActive(this)};
g.h.Af=function(a){U6.dispatchEvent(new PEa(U6,a))};
g.h.Pn=function(){return!(!g.ae||g.Lc(10))};
g.h=$Ea.prototype;g.h.jA=function(){};
g.h.iA=function(){};
g.h.hA=function(){};
g.h.Dt=function(){};
g.h.jB=function(){return{}};
g.h.isActive=function(){return!0};g.B(V6,g.J);g.h=V6.prototype;g.h.fU=function(){this.Gd=Math.min(3E5,2*this.Gd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Gd+15E3*Math.random();g.ev(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Gd=5E3};g.B(W6,$Ea);g.h=W6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Bk=function(a){return this.B.Mi(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.Cb||(this.Cb=!0,g.Bf(this.B),cFa(this),g.Bf(this.A),this.A=null)};
g.h.la=function(){return this.Cb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new N6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Fd=null);d.Fd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.wk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.jc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):X6(this)&&UEa(this.o,c)};
g.h.jA=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)UEa(this.o,a[b])}this.V("handlerOpened")};
g.h.hA=function(a){var b=2==a&&401==this.o.Vf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Dt=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.jB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.jc(a,this.D);return a};
g.h.iA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),SEa(this.o)):this.V("handlerMessage",new aFa(a[0],a[1]))};
g.h.GW=function(){this.A.isActive();var a=this.o,b=0;a.Ac&&b++;a.ie&&b++;0!=b||this.connect(this.D,this.C)};Y6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Y6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Y6.prototype.D=function(a){a(Error("request timed out"))};var kFa=(0,g.H)(),a7=null,d7=Array(50),c7=-1,e7=!1;g.B(f7,g.V);f7.prototype.ye=function(){return this.o};
f7.prototype.contains=function(a){return!!k6(this.o,a)};
f7.prototype.get=function(a){return a?l6(this.o,a):null};
f7.prototype.info=function(a){b7(this.G,a)};g.B(g7,g.V);var sGa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=g7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ia)&&this.aH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ia)||(g.WE(this.Ia),this.Ia=NaN)};
g.h.W=function(){this.stop();g7.ga.W.call(this)};
g.h.aH=function(){this.Ia=NaN;this.o=g.FF(Z6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.IW,this),onError:(0,g.A)(this.HW,this),Kd:(0,g.A)(this.JW,this)})};
g.h.IW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new f6(c))};
g.h.HW=function(a){this.o=null;a.status&&404==a.status?this.A>=sGa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=sGa[this.A],this.Ia=g.UE((0,g.A)(this.aH,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.JW=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(i7,f7);g.h=i7.prototype;g.h.start=function(){h7(this)&&this.V("screenChange");!g.lI("yt-remote-lounge-token-expiration")&&oFa(this);g.WE(this.A);this.A=g.UE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){h7(this);lFa(this,a);j7(this,!1);this.V("screenChange");b(a);a.token||oFa(this)};
g.h.remove=function(a,b){var c=h7(this);nFa(this,a)&&(j7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Qr=function(a,b,c,d){var e=h7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,j7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.W=function(){g.WE(this.A);i7.ga.W.call(this)};
g.h.rL=function(a){h7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}j7(this,!b);b&&b7(this.G,"Missed "+b+" lounge tokens.")};
g.h.qL=function(a){b7(this.G,"Requesting lounge tokens failed: "+a)};g.B(l7,g.V);g.h=l7.prototype;g.h.start=function(){var a=parseInt(g.lI("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?n7(this):(this.C=(0,g.H)()+3E5,g.kI("yt-remote-fast-check-period",this.C),this.jx())};
g.h.isEmpty=function(){return g.bc(this.o)};
g.h.update=function(){k7("Updating availability on schedule.");var a=this.F(),b=g.Lb(this.o,function(b,d){return b&&!!l6(a,d)},this);
m7(this,b)};
g.h.W=function(){g.WE(this.B);this.B=NaN;this.A&&(this.A.abort(),this.A=null);l7.ga.W.call(this)};
g.h.jx=function(){g.WE(this.B);this.B=NaN;this.A&&this.A.abort();var a=rFa(this);if(g.Qb(a)){var b=Z6(this.D,"/pairing/get_screen_availability");this.A=$6(this.D,b,{lounge_token:g.Tb(a).join(",")},(0,g.A)(this.KT,this,a),(0,g.A)(this.JT,this))}else m7(this,{}),n7(this)};
g.h.KT=function(a,b){this.A=null;var c=g.Tb(rFa(this));if(g.rb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;m7(this,d);n7(this)}else this.uc("Changing Screen set during request."),this.jx()};
g.h.JT=function(a){this.uc("Screen availability failed: "+a);this.A=null;n7(this)};
g.h.uc=function(a){b7("OnlineScreenService",a)};g.B(o7,f7);g.h=o7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Qr=function(a,b,c,d){this.B.contains(a)?this.B.Qr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,b7(this.G,a),d(Error(a)))};
g.h.ye=function(a){return a?this.o:g.cb(this.o,(0,g.oe)(this.C,function(a){return!this.contains(a)},this))};
g.h.bH=function(){return(0,g.oe)(this.ye(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.cH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new g7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Bf(f);d(p7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Bf(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.LW=function(a,b,c,d){g.FF(Z6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new f6(d.screen||{});if(!e.name||vFa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);vFa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(p7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Kd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Bf(this.B);g.Bf(this.A);o7.ga.W.call(this)};
g.h.FL=function(){wFa(this);this.V("screenChange");this.A.update()};
o7.prototype.dispose=o7.prototype.dispose;g.B(r7,g.V);g.h=r7.prototype;g.h.Gq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.De=function(a){this.la()||(a&&s7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){b7(this.R,a)};
g.h.eH=function(){return null};
g.h.zx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){s7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.zx("");r7.ga.W.call(this)};g.B(t7,r7);g.h=t7.prototype;g.h.yx=function(a){if(this.o){if(this.o==a)return;s7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);yFa(this)};
g.h.yk=function(a){this.info("launchWithParams no-op for Cast: "+g.Vg(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.De()},this),(0,g.A)(function(){this.De(Error("Failed to stop receiver app."))},this)):this.De(Error("Stopping cast device witout session."))};
g.h.zx=g.z;g.h.W=function(){this.info("disposeInternal");g.WE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;t7.ga.W.call(this)};
g.h.QU=function(a,b){if(!this.la())if(b){var c=g.ay(b);if(g.Ia(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Vg(c));switch(d){case "mdxSessionStatus":xFa(this,c.screenId);break;default:s7(this,"Unknown youtube message: "+d)}}else s7(this,"Unable to parse message.")}else s7(this,"No data in message.")};
g.h.uB=function(a,b,c,d){uFa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(s7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.UE((0,g.A)(this.uB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.eH=function(){return this.o};
g.h.MW=function(a){this.la()||a||(s7(this,"Cast session died."),this.De())};g.B(u7,r7);g.h=u7.prototype;g.h.yx=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.yk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.WE(this.F);this.C?this.C.stop((0,g.A)(this.De,this,null),(0,g.A)(this.De,this,"Failed to stop DIAL device.")):this.De()};
g.h.W=function(){this.o();this.o=g.z;g.WE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;u7.ga.W.call(this)};
g.h.PW=function(a){this.la()||a||(s7(this,"DIAL session died."),this.o(),this.o=g.z,this.De())};
g.h.av=function(a){this.K=j6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,AFa(this));a(b);zFa(this)}else this.G=(0,g.A)(function(){g.WE(this.F);this.G=g.z;this.F=NaN;var b=new chrome.cast.DialLaunchResponse(!0,AFa(this));a(b);zFa(this)},this),this.F=g.UE((0,g.A)(function(){this.G()},this),100)};
g.h.RM=function(a,b,c){uFa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.Gq(a),b(new chrome.cast.DialLaunchResponse(!1))):this.av(b,c)},this),(0,g.A)(function(a){s7(this,"Failed to get DIAL screen: "+a);
this.av(b,c)},this))};g.B(v7,r7);v7.prototype.stop=function(){this.De()};
v7.prototype.yx=g.z;v7.prototype.yk=function(){g.WE(this.o);this.o=NaN;var a=l6(this.J.ye(),this.A.label);a?this.Gq(a):this.De(Error("No such screen"))};
v7.prototype.W=function(){g.WE(this.o);this.o=NaN;v7.ga.W.call(this)};g.B(w7,g.V);g.h=w7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.OE,this),(0,g.A)(this.sT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.oR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.C),hFa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.dH,this)),this.B=CFa(this),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.uc("Failed to set initial custom receivers: "+g.Vg(a))},this)),this.V("yt-remote-cast2-availability-change",y7(this)),b(!0))},this),(0,g.A)(function(a){this.uc("Failed to initialize API: "+g.Vg(a));
b(!1)},this))};
g.h.KV=function(a,b){x7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)x7("Unsetting old screen status: "+this.o.A.friendlyName),z7(this,null)}if(a&&b){if(!this.o){c=l6(this.A.ye(),a);if(!c){x7("setConnectedScreenStatus: Unknown screen.");return}var d=BFa(this,c);d||(x7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(d),chrome.cast.setCustomReceivers(this.B,
g.z,(0,g.A)(function(a){this.uc("Failed to set initial custom receivers: "+g.Vg(a))},this)));
x7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);z7(this,new v7(this.A,d),!0)}this.o.zx(b)}else x7("setConnectedScreenStatus: no screen.")};
g.h.LV=function(a){this.la()?this.uc("Setting connection data on disposed cast v2"):this.o?this.o.yk(a):this.uc("Setting connection data without a session")};
g.h.OW=function(){this.la()?this.uc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),z7(this,null)):x7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.OE,this),(0,g.A)(this.PT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.dH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);g.$a(g.w("yt.mdx.remote.debug.handlers_")||[],eFa);g.Bf(this.o);w7.ga.W.call(this)};
g.h.uc=function(a){b7("Controller",a)};
g.h.PE=function(a,b){this.o==a&&(b||z7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.oT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),x7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)x7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{x7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:z7(this,
new v7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:z7(this,new u7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:z7(this,new t7(this.A,a));break;default:this.uc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.uc("Stopping receiver w/o session: "+a.friendlyName)}else this.uc("onReceiverAction_ called without receiver.")};
g.h.oR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.uc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.uc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.B)return x7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.uc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);z7(this,new u7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.RM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.av,b))};
g.h.OE=function(a){if(!this.la()){x7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)x7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),z7(this,new t7(this.A,b),!0);else{this.uc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=l6(this.A.ye(),c.label);d&&g6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(x7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Bf(this.o),this.o=new t7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.PE,this,this.o)),this.o.yk(null));this.o.yx(a)}}};
g.h.NW=function(){return this.o?this.o.eH():null};
g.h.PT=function(a){this.la()||(this.uc("Failed to estabilish a session: "+g.Vg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&z7(this,null))};
g.h.sT=function(a){x7("Receiver availability updated: "+a);if(!this.la()){var b=y7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;y7(this)!=b&&this.V("yt-remote-cast2-availability-change",y7(this))}};
g.h.dH=function(){this.la()||(this.B=CFa(this),x7("Updating custom receivers: "+g.Vg(this.B)),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.uc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",y7(this)))};
w7.prototype.setLaunchParams=w7.prototype.LV;w7.prototype.setConnectedScreenStatus=w7.prototype.KV;w7.prototype.stopSession=w7.prototype.OW;w7.prototype.getCastSession=w7.prototype.NW;w7.prototype.requestSession=w7.prototype.requestSession;w7.prototype.init=w7.prototype.init;w7.prototype.dispose=w7.prototype.dispose;var F7=[];g.h=K7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";L7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Zf=a.hasPrevious,this.hasNext=a.hasNext,this.D=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.F=a.seekableEnd,this.G=a.duration,this.J=a.loadedTime,this.A=a.liveIngestionTime,this.H=!isNaN(this.A))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.H?this.G+M7(this):this.G};
g.h.clone=function(){return new K7(R7(this))};g.B(T7,g.V);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,Z7(this,"play")):Y7(this,"play"),X7(this,1,O7(U7(this))),this.V("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,O7(U7(this))),this.V("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.V("remotePlayerChange")}else V7(this,g.La(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";L7(a);W7(this,a);this.V("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){b7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.uc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){b7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.uc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.La(this.setVolume,a,b))};
g.h.ZF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Vg(b.style),g.jc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.La(this.ZF,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Qb.id});var c=U7(this);c.audioTrackId=b.Qb.id;W7(this,c)}else V7(this,g.La(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.za(b)&&(N7(l,b),m.currentTime=b);g.za(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Vg(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Nq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.La(this.Nq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.La(this.nextVideo,a,b))};
g.h.JA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.JA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.W=function(){PFa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.W.call(this)};
g.h.zy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.tD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.jT=function(a,b){this.V(a,b)};
g.h.NQ=function(a){if(!a)this.An(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)b7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.An=function(a){b7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),QFa(this),this.V("remotePlayerChange")};
g.h.MQ=function(a){a?(QFa(this),this.V("remotePlayerChange")):this.An(null)};
g.h.Nx=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ZQ=function(){var a=MFa();a&&S7(this,a)};
g.h.uc=function(a){b7("CP",a)};g.B($7,g.V);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.za(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.za(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;N7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.Vg(l));this.o.connect({method:"setPlaylist",
params:g.Vg(l)},a,oEa())}else a8("Connecting without params"),this.o.connect({},a,oEa());SFa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.WE(this.J);this.J=NaN;g.WE(this.K);this.K=NaN;this.B=null;g.IG(this.T);this.T.length=0;this.o.dispose();$7.ga.W.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.hL=function(){this.F(2)};
g.h.RQ=function(){a8("Channel opened");this.N&&(this.N=!1,d8(this),this.R=g.UE((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
sEa(bFa(this.o),this.aa)};
g.h.OQ=function(){a8("Channel closed");isNaN(this.D)?q6(!0):q6();this.dispose()};
g.h.PQ=function(a){q6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.QQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.Vg(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.ay(a.params.devices);this.A=(0,g.I)(a,function(a){return new e6(a)});
a=!!g.Ra(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
VFa(this,a);break;case "loungeScreenDisconnected":g.ab(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
VFa(this,!1);break;case "remoteConnected":var b=new e6(g.ay(a.params.device));g.Ra(this.A,function(a){return b?a.id==b.id:!1})||g.Ya(this.A,b);
break;case "remoteDisconnected":b=new e6(g.ay(a.params.device));g.ab(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":XFa(this,a);break;case "nowPlaying":ZFa(this,a);break;case "onStateChange":YFa(this,a);break;case "onAdStateChange":$Fa(this,a);break;case "onVolumeChanged":aGa(this,a);break;case "onSubtitlesTrackChanged":WFa(this,a);break;case "nowAutoplaying":bGa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":cGa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.rV=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Bk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,isNaN(this.H())?X6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.V("beforeDisconnect",a);1==a&&q6();cFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.fa=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.fa;
$7.prototype.ma=function(a){var b=new K7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.WE(this.J),this.J=g.UE((0,g.A)(this.rV,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&O7(this.qb)==O7(b)&&g.Vg(this.qb.o)==g.Vg(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Ra(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ea=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ea;$7.prototype.da=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.da;$7.prototype.ya=function(){if(!isNaN(this.H())){var a=this.o.A;g.fv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.ya;$7.prototype.ka=function(a,b){f8(this,a,b);UFa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,f7);g.h=g8.prototype;g.h.ye=function(a){return this.ld.$_gs(a)};
g.h.contains=function(a){return!!this.ld.$_c(a)};
g.h.get=function(a){return this.ld.$_g(a)};
g.h.start=function(){this.ld.$_st()};
g.h.add=function(a,b,c){this.ld.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.ld.$_r(a,b,c)};
g.h.Qr=function(a,b,c,d){this.ld.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.ld.$_ubk(this.A[a]);this.A.length=0;this.ld=null;g8.ga.W.call(this)};
g.h.KW=function(){this.V("screenChange")};
g.h.IS=function(){this.V("onlineScreenChange")};
o7.prototype.$_st=o7.prototype.start;o7.prototype.$_gspc=o7.prototype.LW;o7.prototype.$_gsppc=o7.prototype.cH;o7.prototype.$_c=o7.prototype.contains;o7.prototype.$_g=o7.prototype.get;o7.prototype.$_a=o7.prototype.add;o7.prototype.$_un=o7.prototype.Qr;o7.prototype.$_r=o7.prototype.remove;o7.prototype.$_gs=o7.prototype.ye;o7.prototype.$_gos=o7.prototype.bH;o7.prototype.$_s=o7.prototype.subscribe;o7.prototype.$_ubk=o7.prototype.Bk;var h8=null,i8=null,x8=null,m8=[];g.r(y8,g.J);g.h=y8.prototype;
g.h.W=function(){g.J.prototype.W.call(this);this.C.stop();this.F.stop();this.L.stop();this.N();this.o.unsubscribe("proxyStateChange",this.LE,this);this.o.unsubscribe("remotePlayerChange",this.Dn,this);this.o.unsubscribe("remoteQueueChange",this.Hq,this);this.o.unsubscribe("autoplayUpNext",this.iE,this);this.o.unsubscribe("previousNextChange",this.IE,this);this.o.unsubscribe("nowAutoplaying",this.AE,this);this.o.unsubscribe("autoplayDismissed",this.hE,this);this.o=this.D=null};
g.h.kD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Dm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.LQ=function(a){this.L.cL(a)};
g.h.mW=function(a){this.kD("control_subtitles_set_track",g.bc(a)?null:a)};
g.h.oG=function(){var a=this.A.getOption("captions","track");g.bc(a)||C8(this,a)};
g.h.wE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Dn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.Dn,this)}};
g.h.cS=function(){g.bc(this.G)||oGa(this,this.G);this.H=!1};
g.h.LE=function(a,b){this.F.stop();2==b&&this.mG()};
g.h.Dn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.al(1);break;case 1082:case 1083:this.D.al(0);break;default:this.D.al(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.MQ(8));this.lG();break;case 1085:case 3:A8(this,new g.MQ(9));break;case 1083:case 0:A8(this,new g.MQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.MQ(4));break;case 2:A8(this,new g.MQ(4));z8(this,O7(a));
break;case -1:A8(this,new g.MQ(64));break;case -1E3:A8(this,new g.MQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.G=a,oGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.R.isActive()||this.OG()}else nGa(this)};
g.h.IE=function(){this.A.V("mdxpreviousnextchange")};
g.h.Hq=function(){B8(this)||nGa(this)};
g.h.dK=function(){this.o.JA()};
g.h.iE=function(a){a&&(a=g.FF("/watch_queue_ajax",{method:"GET",gd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.rU,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.rU=function(a,b){var c=new g.GP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.AE=function(a){isNaN(a)||this.A.V("mdxnowautoplaying",a)};
g.h.hE=function(){this.A.V("mdxautoplaycanceled")};
g.h.FO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.OG=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.T);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.T=this.B.O(this.A,"onVolumeChange",this.wE)}};
g.h.lG=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.MQ(8));z8(this,O7(a));this.C.start()}};
g.h.mG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.r(E8,g.W);E8.prototype.D=function(a){qGa(this,a.state)};g.r(F8,g.bX);F8.prototype.L=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.H=g.tb(a,this.F,this),g.cX(this,(0,g.I)(a,this.F)),a=this.B.getOption("remote","currentReceiver"),this.zf(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.yf=function(a){return"cast-selector-receiver"==a?"Cast...":this.H[a].name};
F8.prototype.Id=function(a){g.bX.prototype.Id.call(this,a);this.B.setOption("remote","currentReceiver",this.H[a]);this.C.Kb()};g.r(G8,g.nV);g.h=G8.prototype;g.h.create=function(){hGa(g.AN(g.Y(this.player)));this.D.push(g.aF("yt-remote-before-disconnect",this.HQ,this));this.D.push(g.aF("yt-remote-connection-change",this.tT,this));this.D.push(g.aF("yt-remote-receiver-availability-change",this.JE,this));this.D.push(g.aF("yt-remote-auto-connect",this.rT,this));this.D.push(g.aF("yt-remote-receiver-resumed",this.qT,this));this.JE()};
g.h.load=function(){this.player.cancelPlayback();g.nV.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=mGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=O7(U7(b)));0!=a&&this.Ie(a);pGa(this,this.ln,this.ln);g.C0(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.Cf(this.C,this.o);this.o=this.C=null;g.nV.prototype.unload.call(this);g.C0(this.player.app,5)};
g.h.W=function(){g.bF(this.D);g.nV.prototype.W.call(this)};
g.h.Yh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.kD.apply(this.C,[a].concat(g.ea(c)))};
g.h.al=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.WK=function(){return this.loaded?this.C.suggestion:null};
g.h.Zf=function(){return this.o?U7(this.o).Zf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Ie=function(a,b){this.J=a||0;this.player.V("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Nc():!a.isAdPlaying()&&this.player.Nc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.H?a.A+M7(a):a.A,isPeggedToLive:1>=P7(a)-this.getCurrentTime(),isAtLiveHead:1>=P7(a)-this.getCurrentTime(),loaded:a.J,seekableEnd:P7(a),seekableStart:0<
a.B?a.B+M7(a):a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Nq=function(){this.o&&this.o.Nq()};
g.h.HQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.tT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Bf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,O7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.JE=function(){this.F=[this.A].concat(jGa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.rT=function(){var a=s8();H8(this,a)};
g.h.qT=function(){this.B=s8()};
g.h.Jc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?I7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&I7(),!0):!1}};
g.h.Nx=function(){this.o.Nx()};
g.h.xc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.VZ.remote=G8;})(_yt_player);
