(function(g){var window=this;var Gza=function(a,b,c,d){c=(0,g.A)(c,d||a.A);b=g.RG(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},Hza=function(a){a.o||(a.o=new g.$D,g.K(a,a.o));
return a.o},h2=function(a){a.V("cardstatechange",a.ee()&&a.te()?1:0)},Lza=function(a){var b=g.Ph(a,"fontSize");
var c=(c=b.match(Iza))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.ae){if(String(c)in Jza)return g.gi(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in Kza)return a=a.parentNode,c=g.Ph(a,"fontSize"),g.gi(a,b==c?"1em":b,"left","pixelLeft")}c=g.fe("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.ne(c);return b},i2=function(a,b){this.start=a<b?a:b;
this.end=a<b?b:a},Mza=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.hl&&a.dataset){if(g.oc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Cc("pollChoiceIndex"))},l2=function(a){a=g.Ka(a);
delete j2[a];g.bc(j2)&&k2&&k2.stop()},Oza=function(){k2||(k2=new g.U(function(){Nza()},20));
var a=k2;a.isActive()||a.start()},Nza=function(){var a=(0,g.H)();
g.Kb(j2,function(b){Pza(b,a)});
g.bc(j2)||Oza()},Qza=function(a,b){g.Df.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.F;this.state=b.o},m2=function(a,b,c,d){g.Bu.call(this);
if(!g.Fa(a)||!g.Fa(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.G=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.F=0;this.C=null},Pza=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.F=1E3/(b-a.C);a.C=b;Rza(a,a.progress);1==a.progress?(a.o=0,l2(a),a.Jd(),a.Bn()):a.tb()&&a.Cw()},Rza=function(a,b){g.Ha(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.G[c]-a.A[c])*b+a.A[c]},n2=function(a,b,c,d,e){m2.call(this,b,c,d,e);
this.element=a},o2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
n2.apply(this,arguments)},Sza=function(a){return Math.pow(a,3)},Tza=function(a){return 3*a*a-2*a*a*a},p2=function(a,b){(0,g.C)(b,function(b){g.FH("visualElementShown",{csn:a,
ve:g.OH(b),eventType:4},g.KH,void 0,void 0)})},q2=function(a,b){(0,g.C)(b,function(b){g.FH("visualElementHidden",{csn:a,
ve:g.OH(b),eventType:8},g.KH,void 0,void 0)})},r2=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Ld=b.session_data||{};this.B=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.A={NM:a.impression,click:a.click,close:a.close,bW:a.teaser_impression,Kx:a.teaser_click};b=b.tracking_params||{};this.F=g.NH(b.card);this.H=g.NH(b.teaser);this.D=g.NH(b.icon)},s2=function(a,b){g.eg.call(this);
this.Fm=a;this.vu=b;this[g.If]=!1},w2=function(a,b,c,d){s2.call(this,a,b);
a=this.vu;b=this.ra();c?(b.setAttribute("stroke",c.o),b.setAttribute("stroke-opacity",1),c=c.Ya(),g.u(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/Uza(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.vu;a=this.ra();if(d instanceof t2)a.setAttribute("fill",d.J),a.setAttribute("fill-opacity",d.K);else if(d instanceof u2){b="lg-"+d.D+"-"+d.G+"-"+d.F+"-"+d.H+"-"+d.o+"-"+d.A;var e=b in c.A?c.A[b]:null;if(!e){e=v2(c,"linearGradient",{x1:d.D,
y1:d.G,x2:d.F,y2:d.H,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.o;g.Ba(d.B)&&(f+=";stop-opacity:"+d.B);f=v2(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.A;g.Ba(d.C)&&(f+=";stop-opacity:"+d.C);d=v2(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=Vza(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},Wza=function(){},Xza=function(a,b){s2.call(this,a,b)},x2=function(){this.vb=[];
this.Qa=[];this.Ke=[]},y2=function(a,b,c,d){var e=a.he[0]-b*Math.cos(g.Ld(d))+b*Math.cos(g.Ld(d+90)),f=a.he[1]-c*Math.sin(g.Ld(d))+c*Math.sin(g.Ld(d+90));
a.vb.push(3);a.Qa.push(1);a.Ke.push(b,c,d,90,e,f);a.Qn=!1;a.he=[e,f]},Zza=function(a,b){for(var c=a.Ke,d=0,e=0,f=a.vb.length;e<f;e++){var k=a.vb[e],l=Yza[k]*a.Qa[e];
b(k,c.slice(d,d+l));d+=l}},$za=function(a,b,c,d){w2.call(this,a,b,c,d)},z2=function(a,b){this.A=a;
this.o=b},A2=function(a,b,c,d,e){g.Zv.call(this,e);
this.width=a;this.height=b;this.C=c||null;this.R=d||null},Uza=function(a){var b=a.Xj();
return b?b.width/(a.C?new g.Od(a.C,a.R):a.Xj()).width:0},aAa=function(a,b){s2.call(this,a,b)},u2=function(a,b,c,d,e,f,k,l){this.D=a;
this.G=b;this.F=c;this.H=d;this.o=e;this.A=f;this.B=g.za(k)?k:null;this.C=g.za(l)?l:null},t2=function(a,b){this.J=a;
this.K=null==b?1:b},B2=function(a,b){s2.call(this,a,b)},bAa=function(a,b,c,d){w2.call(this,a,b,c,d)},C2=function(a,b){s2.call(this,a,b)},D2=function(a,b,c,d,e){A2.call(this,a,b,c,d,e);
this.A={};this.N=g.ce&&!g.Kc(526);this.K=new g.Mn(this)},v2=function(a,b,c){a=a.J.o.createElementNS("http://www.w3.org/2000/svg",b);
c&&E2(a,c);return a},E2=function(a,b){for(var c in b)a.setAttribute(c,b[c])},F2=function(a,b,c,d){b=v2(a,"path",{d:cAa(b)});
c=new bAa(b,a,c,d);a.B.ra().appendChild(c.ra())},cAa=function(a){var b=[];
Zza(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},Vza=function(a,b,c){if(b in a.A)return a.A[b];
var d="_svgdef_"+dAa++;c.setAttribute("id",d);a.A[b]=d;a.H.appendChild(c);return d},eAa=function(){G2||(G2=new g.Pg(400),G2.start());
return G2},H2=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.I)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.I)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;f.visualElement=g.NH(a.trackingParams);var k=(0,g.I)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,x=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.KA=k.image;l.left=parseFloat(k.left);l.width=parseFloat(k.width);l.top=parseFloat(k.top);l.aspectRatio=parseFloat(k.aspectRatio);
l.startMs=parseInt(k.startMs,10);l.endMs=parseInt(k.endMs,10);l.clickUrls=(0,g.I)(x.loggingUrls||[],c);l.wo=g.Ub(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.I)(k.impressionUrls||[],c);l.aM=(0,g.I)(k.hovercardShowUrls||[],c);l.Ld={itct:k.trackingParams};l.visualElement=g.NH(k.trackingParams);if("VIDEO"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:e(x.watchEndpoint),l.Pp=!1,l.Hr=b,l.videoDuration=d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:
e(x.watchEndpoint),l.Pp=!1,l.Hr=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.Ub(x,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.Pp=!1;l.Hr="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){x=d(m.unsubscribedButtonText);var y=d(m.subscribedButtonText);if(m.subscribed){var E=d(m.subscriberCountWithUnsubscribeText);var G=d(m.subscriberCountText)}else E=d(m.subscriberCountText),G=d(m.subscriberCountWithSubscribeText);
var N=null;if(k.signinEndpoint&&(N=g.Ub(k,"signinEndpoint","webNavigationEndpointData","url"),!N)){k=void 0;break a}if(x&&(y||N)){k={subscribed:m.subscribed,subscribeText:x,subscribeCount:E,unsubscribeText:y,unsubscribeCount:G,enabled:m.enabled,signinUrl:N,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=g.Ub(x,"urlEndpoint","url"),l.Pp=!0,l.Hr="new",l.iconUrl=k.icon.thumbnails[0].url);return l});
f.elements=(0,g.oe)(k,function(a){return!!a});
return f},I2=function(a){g.nV.call(this,a);
this.A=null;this.K=!1;this.C=null;this.o={};this.G={};this.F=this.B=null;this.L=[];a=g.Y(a);this.R=g.AN(a)||g.BN(a);this.pG=!0;this.H=0;this.J=new g.$p(null);this.D=new g.WG(this);g.K(this,this.D);this.D.O(this.player,g.sR("creatorendscreen"),this.JN);this.D.O(this.player,"crx_creatorendscreen",this.KN);this.D.O(this.player,"resize",this.XC);this.D.O(window,"focus",this.KU);this.load();var b=g.he("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Af(this,function(){g.ne(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},fAa=function(a){return a.player.getVideoData().Mc?"current":a.R?"new":"current"},J2=function(a){return"creator-endscreen-editor"===a},K2=function(a,b){g.cV(a.player,"creatorendscreen");
a.B&&(a.B.dispose(),a.B=null,a.F.dispose(),a.F=null);for(var c in a.o)a.o[c].dispose();a.o={};a.G={};0<a.L.length&&(a.L.forEach(function(a){a.dispose()}),a.L.length=0);
a.H=0;if((a.A=b)&&b.elements){gAa(a);c=[];var d=new g.qR(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.Y(a.player).B||(a.B=new g.W({I:"div",M:"ytp-ce-shadow"}),g.eV(a.player,a.B.element,4),a.F=new g.LV(a.B,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=hAa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.eV(a.player,f.element,4);var k=new g.qR(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);iAa(a,f,e)}g.$U(a.player,
c);a.XC()}},gAa=function(a){var b=g.eI(),c=g.fI();
c&&b&&g.PH(c,b,[a.A.visualElement])},hAa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={I:"div",ca:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.wo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-covering-image",U:L2(b)},{I:"div",M:"ytp-ce-covering-shadow-top"},{I:"a",M:"ytp-ce-covering-overlay",U:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",ca:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],U:{dir:g.aq(a.J,b.title||"")},ba:b.title},{I:"div",M:"ytp-ce-video-duration",ba:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={I:"div",ca:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.wo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-covering-image",U:L2(b)},{I:"div",M:"ytp-ce-covering-shadow-top"},{I:"a",M:"ytp-ce-covering-overlay",U:{href:b.targetUrl,tabindex:"-1"},P:[{I:"div",ca:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],U:{dir:g.aq(a.J,b.title||"")},ba:b.title},{I:"div",M:"ytp-ce-playlist-count",P:[{I:"div",
M:"ytp-ce-playlist-icon"},{I:"div",M:"ytp-ce-playlist-count-text",ba:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={I:"div",ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.wo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-expanding-overlay",P:[{I:"div",M:"ytp-ce-expanding-overlay-hider"},{I:"div",M:"ytp-ce-expanding-overlay-background"},{I:"div",M:"ytp-ce-expanding-overlay-content",
P:[{I:"div",M:"ytp-ce-expanding-overlay-body",P:[{I:"div",M:"ytp-ce-expanding-overlay-body-padding",P:[{I:"a",ca:["ytp-ce-channel-title","ytp-ce-link"],U:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.aq(a.J,b.title||"")},ba:b.title},b.subscribeButton?{I:"div",M:"ytp-ce-subscribe-container",P:[{I:"div",M:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",M:"ytp-ce-channel-subscribers-text",ba:b.subscribersText}:"",b.metadata?{I:"div",ca:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ba:b.metadata}:""]}]}]}]},{I:"div",M:"ytp-ce-expanding-image",U:L2(b)}]};c=new g.W(c);var d=g.Ud(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.S(d,"ytp-ce-subscribe-button");if(g.Y(a.player).B){var e=null;var f=b.Ld.itct}else e="endscreen",f=null;e=new g.x_(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.L.push(e)}break;case "WEBSITE":c={I:"div",ca:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.wo||"","aria-hidden":"true"},P:[{I:"div",M:"ytp-ce-element-shadow"},{I:"div",M:"ytp-ce-expanding-overlay",P:[{I:"div",M:"ytp-ce-expanding-overlay-hider"},{I:"div",M:"ytp-ce-expanding-overlay-background"},{I:"div",M:"ytp-ce-expanding-overlay-content",P:[{I:"div",M:"ytp-ce-expanding-overlay-body",
P:[{I:"div",M:"ytp-ce-expanding-overlay-body-padding",P:[{I:"div",M:"ytp-ce-website-title",U:{dir:g.aq(a.J,b.title||"")},ba:b.title},{I:"div",M:"ytp-ce-website-metadata",ba:b.metadata},{I:"a",ca:["ytp-ce-website-goto","ytp-ce-link"],U:{href:b.targetUrl,target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},{I:"div",M:"ytp-ce-expanding-image",U:L2(b)},{I:"div",M:"ytp-ce-expanding-icon",U:jAa(b.iconUrl)}]},c=new g.W(c)}b.o&&g.S(c.element,"ytp-ce-placeholder");return c},L2=function(a){if(a.KA)var b=
a.KA.thumbnails;
return jAa(b?b[b.length-1].url:null)},jAa=function(a){return a?{style:"background-image: url("+a+")"}:{}},iAa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.X("mouseenter",(0,g.A)(a.Tv,a,b,c));b.X("mouseleave",(0,g.A)(a.Kw,a,b,c));g.Y(a.player).B||b.X("click",(0,g.A)(function(a){g.S(a.element,"ytp-ce-element-hover")},a,b));
b.X("click",(0,g.A)(a.rE,a,c));b.X("keypress",(0,g.A)(a.rE,a,c));b.X("focus",(0,g.A)(function(a,b){this.Tv(a,b)},a,b,c));
b.X("blur",(0,g.A)(function(a,b){this.Kw(a,b)},a,b,c));
b.X("touchstart",(0,g.A)(a.Tv,a,b,c));var f=g.Wd("ytp-ce-expanding-overlay-hider",b.element);f&&b.O(f,"touchstart",function(a){g.NG(a);g.pr(b.element,"ytp-ce-element-hover");g.pr(b.element,"ytp-ce-force-expand")});
b.X("keydown",(0,g.A)(function(a,b){this.pG=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.A)(function(a,b,c){this.H+=c;0<this.H?(g.S(a.element,"ytp-ce-force-expand"),M2(this,b.id,!0)):(g.pr(a.element,"ytp-ce-force-expand"),g.pr(a.element,"ytp-ce-element-hover"),M2(this,b.id,!1))},a,b,c);
a=(0,g.A)(function(a,b){b&&(a.X("blur",function(){g.fi(b)&&this.pG&&b.focus()}),a.O(b,"focus",d),a.O(b,"blur",e))},a,b);
a(g.Wd("ytp-sb-subscribe",b.element));a(g.Wd("ytp-sb-unsubscribe",b.element));b.X("focus",d);b.X("blur",e)},M2=function(a,b,c){a.B&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.T(a.o[d].element,"ytp-ce-element-shadow-show",c)},N2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||J2(g.Y(a.player).playerStyle))c&&c();else{b=kAa(a,b);var e=0,f=!1,k=new g.U(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.aG(b[a],d)}},O2=function(a,b,c){N2(a,b.clickUrls,c);
(a=g.fI())&&b.Pp&&g.RH(a,b.visualElement)},kAa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(lAa(b[e],c));return d},lAa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=unescape(a);
c=c.substring(1,c.length-1);return b[c]?escape(b[c]):a})},P2=function(a){return g.Fa(a)&&a.length?a[0]:a},Q2=function(a){var b=/.+/;
return g.u(a)&&null!=b&&null!=a&&a.match(b)?a:""},R2=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},S2=function(a){return g.u(a)?a:""},T2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},U2=function(a,b){return"true"==a||"false"==a?"true"==a:b},V2=function(a,b){return g.u(a)?parseFloat(a):b},W2=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Gd(a,b,c);if(a>=b&&a<=c)return a}return e},mAa=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.C)(a,function(a){a=parseFloat(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},X2=function(a,b){if(null==a)return null;
if(g.Ga(a)){var c=[];(0,g.C)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},nAa=function(a){function b(a){return null!=a&&!isNaN(a)}
return(a=a?new g.uh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},oAa=function(a){function b(a){return(0,g.oe)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},pAa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},Y2=function(a){if(!a)return null;
var b=g.gd(S2(a.value));b=g.dd(b);if(!b)return null;var c=T2(a.target,qAa,"current");return null==c?null:new pAa(b,c,U2(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},Z2=function(a){return a.value?a.value:null},rAa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},uAa=function(a){if(!a)return null;
var b=T2(a.type,sAa),c=T2(a.trigger,tAa),d=P2(a.url);d=Y2(d?d:null);P2(a.subscribeData);return b?new rAa(b,c,d):null},vAa=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},$2=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},a3=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.xl=c;this.B=d;this.t=e;this.D=f;this.F=k;this.G=l;this.C=m;this.A=n;this.o=p},xAa=function(a,b){if(!a)return null;
var c=V2(a.x,0),d=V2(a.y,0),e=V2(a.w,0),f=V2(a.h,0),k=mAa(a.t),l=V2(a.d,0),m=V2(a.px,0),n=V2(a.py,0),p=V2(a.scaleSlope,1),t=V2(a.scaleSlopeX,p);p=V2(a.scaleSlopeY,p);var x=T2(a.scaleDimension,wAa,"xy");return b(c,d,e,f,k,l,m,n,t,p,x)},b3=function(a,b){var c=yAa(b,zAa(a,new g.xh(a.x,a.y,a.xl,a.B),b.o)),d=b.o,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Gd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Gd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},zAa=function(a,b,c){var d=a.F,e=a.G,f=a.o?a.o:"xy",k=vAa(c,a.C,f);
a=$2(c,a.A,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.xh(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},AAa=function(a){return a?xAa(a,function(a,c,d,e,f,k,l,m,n,p,t){return new a3(a,c,d,e,f,k,l,m,n,p,t)}):null},BAa=function(a,b){this.o=a;
this.A=b||null},yAa=function(a,b){var c=a.A?b3(a.A,new BAa(a.o)):a.o;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.Md?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ba(c)&&(d.top+=c));return d},CAa=function(a,b,c,d,e,f,k,l,m,n,p,t,x){a3.call(this,a,b,c,d,e,l,m,n,p,t,x);
this.H=f;this.J=k},DAa=function(a){if(!a)return null;
var b=V2(a.sx,0),c=V2(a.sy,0);return xAa(a,function(a,e,f,k,l,m,n,p,t,x,y){return new CAa(a,e,f,k,l,b,c,m,n,p,t,x,y)})},EAa=function(a,b,c,d,e,f,k,l,m,n,p,t,x,y){this.A=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.o=e;this.F=f;this.B=k;this.textAlign=l;this.textSize=m;this.C=n;this.padding=p;this.effects=t;this.cornerRadius=x;this.D=y},GAa=function(a){if(!a)return null;
var b=R2(a.fgColor,"#1A1A1A"),c=R2(a.bgColor,"#FFF"),d=R2(a.borderColor,"#000"),e=W2(a.borderWidth,0,5,!1,0),f=W2(a.bgAlpha,0,1,!1,.8),k=R2(a.highlightFontColor,"#F2F2F2"),l=W2(a.highlightWidth,0,5,!1,3),m=S2(a.textAlign),n=W2(a.textSize,3.3,30.1,!0,3.6107),p=S2(a.fontWeight),t=nAa(a.padding),x=oAa(a.effects),y=W2(a.cornerRadius,0,10,!0,0);a=P2(a.gradient);if(a=a?a:null){var E=W2(a.x1,0,100,!0,0),G=W2(a.y1,0,100,!0,0),N=W2(a.x2,0,100,!0,100),O=W2(a.y2,0,100,!0,100),sa=R2(a.color1,"#FFF"),kb=R2(a.color2,
"#000");a=new FAa(E,G,N,O,sa,kb,W2(a.opacity1,0,100,!0,100),W2(a.opacity2,0,100,!0,0))}else a=null;return new EAa(b,c,d,e,f,k,l,m,n,p,t,x,y,a)},FAa=function(a,b,c,d,e,f,k,l){this.B=a;
this.D=b;this.C=c;this.F=d;this.o=e;this.A=f;this.G=k;this.H=l},HAa=function(a,b,c,d){this.type=a;
this.A=b;this.o=c;this.B=d},JAa=function(a){if(!a)return null;
var b=T2(a.type,IAa,"rect"),c=X2(a.rectRegion,AAa),d=X2(a.anchoredRegion,DAa);a=X2(a.shapelessRegion,AAa);return new HAa(b,c,d,a)},KAa=function(a){return a.A&&a.A.length?a.A[0]:a.o&&a.o.length?a.o[0]:a.B&&a.B.length?a.B[0]:null},LAa=function(a,b){this.A=a;
this.o=b},MAa=function(a,b){this.state=a;
this.ref=b},OAa=function(a){if(!a)return null;
var b=T2(a.state,NAa);a=Q2(a.ref);return b?new MAa(b,a):null},PAa=function(a,b,c,d){this.o=a||[];
this.B=b||[];this.C=c;this.A=d;this.value=!1},QAa=function(a){if(!a)return null;
var b=X2(a.condition,OAa),c=X2(a.notCondition,OAa),d=U2(a.show_delay,!1);a=U2(a.hide_delay,!1);return b||c?new PAa(b,c,d,a):null},RAa=function(a,b,c){(0,g.C)(a.o,g.La(b,!1),c);
(0,g.C)(a.B,g.La(b,!0),c)},c3=function(a,b,c,d,e,f,k,l,m,n,p,t,x,y){this.id=a;
this.author=b;this.type=c;this.style=d;this.C=e;this.segment=f;this.B=k||[];this.G=l||[];this.A=m;this.F=n;this.D=p;this.data=t;this.o=x;this.itct=y},UAa=function(a){if(!a)return null;
var b=Q2(a.id),c=Q2(a.author),d=T2(a.type,SAa),e=T2(a.style,d3),f=S2(P2(a.TEXT)),k=S2(a.data);k=0!=k.length?JSON.parse(k):{};var l=P2(a.segment);var m=l?l:null;m?(Q2(m.timeRelative),l=Q2(m.spaceRelative),l=(m=X2(m.movingRegion,JAa))?new LAa(l,m):null):l=null;m=X2(a.action,uAa);var n=X2(a.trigger,QAa),p=P2(a.appearance);(p=GAa(p?p:null))||(p=GAa({}));var t=T2(a.coordinate_system,TAa,"video_relative"),x=U2(a.closeable,!0),y=S2(a.log_data);a=S2(a.itct);return b&&d?new c3(b,c,d,e,f,l,m,n,p,t,x,k,y,a):
null},f3=function(a){return e3(a,function(a){return"click"==a.trigger})},e3=function(a,b){return(0,g.ck)(a.B,b,void 0)},VAa=function(a,b,c){(0,g.C)(a.B,b,c)},WAa=function(a,b){return g.Ra(a.B,b,void 0)},XAa=function(a,b,c){(0,g.C)(a.G,b,c)},YAa=function(a,b){(0,g.I)(a.G,b,void 0)},g3=function(a){return(a=ZAa(a))?KAa(a):null},ZAa=function(a){a.segment?(a=a.segment,a=a.o.length?a.o[0]:null):a=null;
return a},$Aa=function(a,b){var c=g3(a);
return c&&b?$2(b,c.A,c.o?c.o:"xy"):1},bBa=function(a,b,c){this.o={};
this.B=!1;this.D="ivTrigger:"+a;this.A=c;RAa(b,function(a,b){var c=aBa(b.state,b.ref);this.A.subscribe(c,(0,g.A)(this.C,this,c,a));this.o[c]=a},this)},aBa=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},h3=function(){this.o=!1;
this.D=this.A=null},i3=function(a,b,c){a.A?(a.A.setSize(b,c),a.A.clear()):(b=new D2(b,c,void 0,void 0,void 0),a.A=b,a.A.zp(),a.D=g.fe("DIV"),b=a.A.ra(),a.D.appendChild(b));
return a.A},j3=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Kb(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},k3=function(a,b){var c=":"+(g.Yv.getInstance().o++).toString(36);
b.setAttribute("result",c);a.appendChild(b);return c},cBa=function(a,b){var c=k3(a,j3("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=k3(a,j3("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},j3("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=k3(a,j3("feComposite",{"in":c,in2:b,operator:"in"}));return k3(a,j3("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},dBa=function(a,b){var c=k3(a,j3("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=k3(a,j3("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=k3(a,j3("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=k3(a,j3("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=k3(a,j3("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=k3(a,j3("feComposite",{operator:"out","in":c,in2:d}));return k3(a,j3("feComposite",{operator:"over","in":b,in2:c}))},eBa=function(a,b){return b},fBa=function(a){var b=
j3("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.C)(a,function(a){a:{switch(a){case "bevel":a=cBa;break a;case "dropshadow":a=dBa;break a}a=eBa}c=a(b,c)});
return b},gBa=function(a){a=(0,g.oe)(a,function(a){return a in l3});
g.qb(a,function(a,c){return l3[a]-l3[c]});
return a},hBa=function(a){return g.Ra(a,function(a){return"dropshadow"==a})?new g.uh(0,7,7,0):new g.uh(0,0,0,0)},iBa=function(a,b,c){var d=new x2;
d.moveTo(a.left+b+c,a.top+c);d.Lc(a.left+a.width-b-c,a.top+c);y2(d,b,b,-90);d.Lc(a.left+a.width-c,a.top+a.height-b-c);y2(d,b,b,0);d.Lc(a.left+b+c,a.top+a.height-c);y2(d,b,b,90);d.Lc(a.left+c,a.top+b+c);y2(d,b,b,180);d.close();return d},jBa=function(a,b,c,d){var e=a.D;
e?a=new u2(e.B*b/100,e.D*c/100,e.C*b/100,e.F*c/100,e.o,e.A,e.G,e.H):(b=a.o,a=new t2(a.bgColor,d?Math.max(b,.9):b));return a},m3=function(a,b){var c=g.yh(a);
c.expand(hBa(b));return new g.xh(c.left,c.top,c.right-c.left,c.bottom-c.top)},kBa=function(a,b,c){if(c.length&&(b=g.Ud(document,"g",void 0,b),b.length)){var d=gBa(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.A?a.A[c]:null;e?a=e:(d=fBa(d),a=0<d.childNodes.length?Vza(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},n3=function(){h3.call(this);
this.C=0},lBa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},o3=function(a){h3.apply(this,arguments)},p3=function(a){h3.apply(this,arguments)},q3=function(a){n3.apply(this,arguments)},r3=function(a,b,c,d,e){g.J.call(this);
this.o=a;this.Z=b;this.F=c;this.fa=d;this.da=e;this.J=!1;this.Y=new g.TG(this);g.K(this,this.Y);this.N=this.D=this.G=this.R=this.A=null;this.aa=!1;this.ea=this.K=this.L=null;this.Bq=new g.bm(this.tL,100,this);g.K(this,this.Bq);this.H=new g.U(this.SB,500,this);g.K(this,this.H);this.T=this.B=this.C=null},mBa=function(a,b){var c=(0,g.A)(function(a,c,f){c=f?s3(this,c,(0,g.A)(f,this)):s3(this,c);
this.Y.X(b,a,c)},a);
c("mouseover","G",a.gD);c("mouseout","F",a.Zh);c("click","D");c("touchend","D")},nBa=function(a){if(a.o.D){if(e3(a.o,function(a){return"close"==a.type}))var b=a.A;
else a.C=g.fe("DIV","annotation-close-button"),g.L(a.C,!1),g.RE(a.C,"annotation_id",a.o.id),a.A.appendChild(a.C),b=a.C;var c=function(a){a.stopPropagation()};
a.Y.X(b,"click",s3(a,"E",c));a.Y.X(b,"touchend",s3(a,"E",c))}},s3=function(a,b,c){return(0,g.A)(function(a){if(this.da)c&&c(a);
else if(a.event.target instanceof Element){var d=a.event.target;g.L(d,!1);try{var f=document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.Ce(f,"annotation")){var k=document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.L(d,
!0)}}d=g.di(a.target);a=new g.Md(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.fa.V(b,this.o)},a)},u3=function(a){if(a.A||a.B){var b=g3(a.o);
if(b){var c=t3(a);if(a.A){b=b3(b,c);var d=g.RU(a.F).getVideoContentRect();g.bi(a.A,b.width,b.height);g.Rh(a.A,b.left,b.top);a.R=new g.xh(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=g3(a.o))&&d?vAa(d,e.C,e.o?e.o:"xy"):1;var f=$Aa(a.o,d);d=a.o.A;d.padding?d=d.padding:(d="speech"==a.o.style?1.6:.8,d=new g.uh(d,d,d,d));d=new g.uh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.D&&(d.right+=1.5*c.o.height/100);a.A.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+
d.left+"px";"label"==a.o.style&&a.G&&(a.G.style.padding=a.A.style.padding);d=c.o;var k=!1,l=0,m=0;var n=g.RU(a.F).getVideoContentRect();var p=g.YU(a.F);g.zh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.o.F&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.D){f=oBa(a,23,b,d,e);if(a.C){var t=43-f.width;0<t&&(b.left+f.left-t>n.left&&(f.left-=t),f.width+=t)}t=f;g.bi(a.D,f.width,f.height);g.Rh(a.D,f.left,f.top)}a.C&&
(t?b=new g.Md(t.left+t.width-23-18,a.aa?t.top+2:t.top+t.height-18-2):(t=oBa(a,18,b,d,e),b=new g.Md(t.left,t.top),g.bi(a.C,t.width,t.height)),g.Rh(a.C,b));a.N=new g.xh(a.R.left+t.left,a.R.top+t.top,t.width,t.height);a.L=a.Y.X(g.RU(a.F),"mousemove",a.zO,a)}else a.D&&(t=e/f*d.height*4.2/100,t=new g.Od(t,t),"highlight"==a.o.type||"label"==a.o.style?(e=1.5*d.height/100,t=new g.xh(b.width-t.width-e,b.height-t.height-e,t.width,t.height)):t=new g.xh(b.width-t.width-3*d.height/100,(b.height-t.height)/2,t.width,
t.height),g.bi(a.D,t.width,t.height),g.Rh(a.D,t.left,t.top)),a.C&&(t=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Rh(a.C,t&&e?new g.Md(b.width-9,-9):t?new g.Md(b.width-9,45<b.height?9:b.height-9):e?new g.Md(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.Md(45<b.width?b.width-9-18:-9,b.height-9):new g.Md(-9,45<b.height?9:b.height-9)))}a.B&&a.B.B(a.o,c);if(a.A){c=a.A;b=a.o.A;c.style.color="highlightText"==a.o.style?b.F:b.A;t=g.RU(a.F).getVideoContentRect();c.style.fontSize=
360*b.textSize*$Aa(a.o,t)/100+"px";t=a.o.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==t||"highlightText"==t?"center":"left";b.C&&(c.style.fontWeight=b.C);a=a.A;c=a.style.overflow;t=(b=g.Wd("annotation-link-icon",a))?g.fi(b):!1;e=(d=g.Wd("annotation-close-button",a))?g.fi(d):!1;t&&g.L(b,!1);e&&g.L(d,!1);m=f="";if(n=g.Wd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>
a.offsetWidth){l=k=Lza(a);p=5;for(var x=Math.floor(k/2);x;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+x,k)):l=Math.max(l-x,p),x=Math.floor(x/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.L(d,!0);t&&g.L(b,!0)}}}},oBa=function(a,b,c,d,e){var f=0<e;
b=new g.xh(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.S(a.A,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.S(a.A,"annotation-extend-up"),a.aa=!0);return b},v3=function(a){return"label"!=a.o.style||a.B.o},t3=function(a){var b=g.RU(a.F).getVideoContentRect();
if("player_relative"==a.o.F){var c=g.RU(a.F).getPlayerSize();b=new g.xh(-b.left,-b.top,c.width,c.height)}else b=new g.xh(0,0,b.width,b.height);return new BAa(b,a.T?g3(a.T):null)},pBa=function(a,b){return b?new g.xh(a.x+b.left,a.y+b.top,b.width,b.height):null},w3=function(a,b,c){g.J.call(this);
this.A=a;this.annotation=b;this.view=c;this.o=null;this.B=this.isVisible=!1;qBa(b,a)},qBa=function(a,b){YAa(a,function(c){return new bBa(a.id,c,b)})},rBa=function(a){a.A.unsubscribe("resize",a.fD,a);
a.A.unsubscribe("onVideoAreaChange",a.WE,a)},x3=function(a){a.o&&(a.o.stop(),a.o=null)},sBa=function(a,b,c){r2.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},y3=function(a,b,c){r2.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.C=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.o=null;if(a=b.signin_url)this.o=Y2({target:"current",value:a});this.L=b.signin_title||null;this.K=b.signin_message||null},tBa=function(a,b,c){y3.call(this,a,b,c);
this.J=b.ypc_flow_type;this.G=b.innertube_request_params},uBa=function(a,b,c){r2.call(this,a,b,c);
this.C=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},vBa=function(a,b,c){r2.call(this,a,b,c);
this.G=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.o=b.hasOwnProperty("old_vote")?b.old_vote:null;this.C=null;if(a=b.signin_url)this.C=Y2({target:"current",value:a});this.J=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},xBa=function(a,b,c){y3.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new wBa(a[b]))},wBa=function(a){this.merchant=g.F(a.merchant);
this.price=g.F(a.price)},yBa=function(a,b,c){y3.call(this,a,b,c);
this.R=b.ypc_item_type;this.J=b.ypc_item_id;this.G=b.ypc_flow_type},zBa=function(a,b,c){r2.call(this,a,b,c);
this.C=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=Y2({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},z3=function(a,b,c){r2.call(this,a,b,c);
this.J=b.image_url;this.C=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.G=!!b.is_paygated;this.K=!!b.user_has_entitlement;this.url=Y2({target:b.target||"new",value:b.url})},ABa=function(a){this.o=a;
this.A={}},BBa=function(a){var b={};
b=(b["iv-event"]=1,b);g.XU(a.o,"iv",b,void 0)},D3=function(a,b,c,d){if(b){var e=A3(a,b);
a.A[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=B3(a,"cta_annotation_shown",e,c);C3(a,e,CBa(b,d))}},E3=function(a,b,c,d,e,f){if(b){var k=A3(a,b);
k["iv-event"]=3;k["i-time"]=a.A[b]||"";d&&g.jc(k,d);b=B3(a,"cta_annotation_clicked",k,e);C3(a,k,b,c,f)}},F3=function(a,b){if(b){var c=A3(a,b);
c["iv-event"]=4;c["i-time"]=a.A[b]||"";var d=B3(a,"cta_annotation_closed",c);C3(a,c,d)}},CBa=function(a,b){return b?(0,g.I)(a,g.La(function(a,b){return g.Un(b,a)},b)):a},B3=function(a,b,c,d){d=d?g.db(d):[];
var e=c["a-type"];if(30==e||31==e&&g.Y(a.o).experiments.o("enable_async_click_tracking")){a:{c=c["a-id"];a=a.o.getVideoData();if(a.Qz){if((b=a.Qz[b])&&g.XJ(b)){a=g.pc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Sq){b=g.xF(a.Sq,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},C3=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.C)(c||[],function(a){f++;
g.aG(a,m)});
e&&(f++,0!=e&&a.o.sendVideoStatsEngageEvent(e,m));g.XU(a.o,"iv",b,m)},A3=function(a,b){var c={};
if(b){var d=new g.Dn(b);(0,g.C)(d.Hb(),function(a){c[a]=escape(d.get(a,""))})}c["p-time"]=a.o.getCurrentTime().toFixed(2);
c.ps=g.Y(a.o).playerStyle;return c},G3=function(a,b,c,d,e){e=A3(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;C3(a,e,d)},H3=function(a,b,c,d){c&&(c=A3(a,c),c["iv-event"]=b,C3(a,c,d))},DBa=function(a,b,c,d,e,f,k){this.A=a;
this.C=b;this.D=c;this.videoData=d;this.logger=e;this.o=f;this.B=k},I3=function(a,b,c){this.o=a;
this.C=b;this.D=c;this.A=new g.$p(null)},FBa=function(a,b){var c=[];
(0,g.C)(b.choices,function(a){c.push({I:"li",M:b.G+"-"+a.index.toString(),P:[{I:"label",P:[{I:"input",M:"iv-card-poll-choice-input",U:{type:"checkbox",role:"radio",name:b.G+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{I:"span",M:"iv-card-poll-choice-text",P:[{I:"span",M:"iv-card-poll-choice-percent"},J3(this,"span",void 0,a.desc)]}]},{I:"div",M:"iv-card-poll-result",P:[{I:"div",M:"iv-card-poll-result-bar"}]}]})},a);
var d={I:"ul",U:{role:"radiogroup"},P:c},e={};b.C&&(e["aria-label"]=g.DV("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{I:"div",M:"iv-card-content",P:[J3(a,"h2",e,b.title),{I:"form",P:[{I:"fieldset",P:[d]}]}]}];b.C&&(f.push("iv-card-unavailable"),d.push({I:"div",ca:["iv-card-sign-in"],P:[{I:"h2",ba:"Want to vote?"},{I:"a",ca:["iv-card-sign-in-button","iv-button"],U:{href:Z2(b.C)},P:[{I:"span",ca:["iv-button-content"],ba:"Sign in"}]}]}));f=new g.W({I:"div",
ca:f,P:d});d=f.element;EBa(b,d);Gza(a.o.A,d,g.La(a.G,b),a);(0,g.C)(g.Vd("iv-card-poll-choice-input",d),function(a){this.o.A.X(a,"focus",g.La(this.B,!0));this.o.A.X(a,"blur",g.La(this.B,!1))},a);
b.C&&(d=g.Wd("iv-card-sign-in-button",d),a.C(d,b.C,b.id,b.Ld,b.B,b.A.click,5));return f},M3=function(a,b,c,d){var e=b.displayDomain?{I:"div",
M:"iv-card-image-text",ba:b.displayDomain}:"",f=GBa(a,b),k=["iv-card"];b.o&&k.push("iv-card-unavailable");e=[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.imageUrl,e),{I:"div",M:"iv-card-content",P:[J3(a,"h2",void 0,b.title),f]}]}];b.o&&e.push({I:"div",ca:["iv-card-sign-in"],P:[J3(a,"h2",void 0,b.L||""),{I:"p",ba:b.K},{I:"a",ca:["iv-card-sign-in-button","iv-button"],U:{href:Z2(b.o)},P:[J3(a,"span","iv-button-content","Sign in")]}]});k=new g.W({I:"div",ca:k,P:e});L3(a,k,b,c,d);return k},HBa=
function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.K?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.G&&b.C?{I:"span",ca:d,U:e,ba:b.C}:"";c={I:"div",ca:["iv-card",c],P:[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.J,d?{I:"div",M:"iv-card-image-text",P:[d,b.priceText]}:""),{I:"div",M:"iv-card-content",P:[{I:"h2",M:"iv-card-primary-link",ba:b.title},N3(a,b)]}]}]};c=new g.W(c);L3(a,c,b);return c},O3=function(a,b){return b.customMessage?J3(a,"div",
"iv-card-message",b.customMessage):""},K3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{I:"div",M:"iv-card-image",U:{style:c},P:d}},N3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.C)(b.metaInfo,function(a){c.push(J3(this,"li","",a))},a);
return{I:"ul",M:"iv-card-meta-info",P:c}},J3=function(a,b,c,d){c?g.u(c)?c={"class":c}:g.Fa(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.aq(a.A,d);return{I:b,U:c,ba:d}},GBa=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.C&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.C+");");d.dir=g.aq(a.A,b.customMessage);var e=[{I:"span",ba:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({I:"span",M:"iv-card-link-icon"}));return{I:"div",ca:c,U:d,P:e}},EBa=function(a,b){var c=0;
(0,g.C)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Wd(a.G+"-"+e.index.toString(),b);e=e.count/c;null==a.o&&(e=0);g.T(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.o==d);f.getElementsByTagName("input")[0].checked=a.o==d;var k=Math.floor(100*e).toFixed(0),l=g.Wd("iv-card-poll-choice-percent",f);g.ve(l,g.DV("$PERCENT%",{PERCENT:k}));f=g.Wd("iv-card-poll-result-bar",f);g.Kh(f,"transform","scaleX("+e.toFixed(2)+")")}g.T(b,"iv-card-poll-voted",null!=a.o);g.T(b,"iv-card-poll-expanded",
null!=a.o&&1<a.choices.length)},IBa=function(a,b,c,d){d?(c&&a.o.videoData.Da||a.o.o.pauseVideo(),a.o.o.isFullscreen()&&a.o.o.toggleFullscreen(),E3(a.o.logger,b.B,d,void 0,b.A.click,5),(a=g.fI())&&g.RH(a,b.F)):b.url&&a.D(b.url,b.id,b.Ld,b.B,b.A.click||[],5)},L3=function(a,b,c,d,e){c.o&&JBa(a,g.Vd("iv-card-sign-in-button",b.element),c,c.o,e);
c.url&&JBa(a,g.Vd("iv-click-target",b.element),c,c.url,d)},JBa=function(a,b,c,d,e){(0,g.C)(b,function(a){if(e){var b=(0,g.A)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.o.A.X(a,"click",b)}else d&&this.C(a,d,c.id,c.Ld,c.B,c.A.click,5)},a)},KBa=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},P3=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=LBa(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},LBa=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},MBa=function(a){a=Z2(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!P3(a))||(b=g.bh(g.ah(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.vF(a);if(!b||!b.v)return null;if(b=b.t)return KBa(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.tF(a[1]))&&a.t?KBa(a.t):-1},NBa=function(a){a=Z2(a);
a=a.replace(/https?:\/\//g,"");return P3(a)?(a=g.vF(a))&&a.v?a.v:null:null},OBa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},Q3=function(a,b){return b?b:P3(a)?"current":"new"},R3=function(a,b){g.J.call(this);
this.Ea=a;this.context=b;this.my=!1;this.fa=0},PBa=function(a){return(0,g.H)()-a.fa},QBa=function(a,b,c,d,e,f){var k=Z2(b);
if(k){var l=Q3(k,b.target),m=(0,g.A)(function(){b.o&&this.context.o.pauseVideo();var a=this.context.videoData.Mc||!1,d=g.vF(k||"");a&&d&&(d.v||d.list)?g.L0(this.context.o.app,d.v,c,d.list,!1,void 0,void 0):g.AV(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=PBa(a);E3(a.context.logger,d,m,n,e,f);P3(k)||(a=g.fI(),d=c.itct,a&&d&&g.RH(a,g.NH(d)))}},U3=function(a,b,c){R3.call(this,b,c);
var d=this;this.A=a;this.Z=null;this.aa=this.za=this.D=this.ya=!1;this.ea=null;this.N=new g.U(g.z,c.D.td?4E3:3E3);g.K(this,this.N);this.ma=new g.U(g.z);g.K(this,this.ma);this.F=new I3(c,(0,g.A)(this.fl,this),(0,g.A)(this.Yp,this));this.J=new g.W({I:"div",M:"iv-drawer",U:{id:"iv-drawer"},P:[{I:"div",M:"iv-drawer-header",U:{"aria-role":"heading"},P:[{I:"span",M:"iv-drawer-header-text"},{I:"button",ca:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",M:"iv-drawer-content"}]});
g.K(this,this.J);this.G=this.J.element;this.ia=new g.LV(this.J,330);g.K(this,this.ia);this.Aa=g.Wd("iv-drawer-header-text",this.G);this.C=g.Wd("iv-drawer-content",this.G);this.B=[];this.sa=this.T=this.H=this.da=this.o=null;this.L=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.za&&S3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.za=d.D)&&T3(d)});
this.R=this.K=this.ha=null},WBa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&RBa[c]){c=new RBa[c](b.id,b.data,b.o);if(!a.ya){g.or(a.ra(),["html5-stop-propagation","iv-drawer-manager"]);g.eV(a.A,a.G,5);SBa(a);a.T=g.Wd("ytp-cards-button",a.A.getRootNode());var d=g.Wd("iv-drawer-close-button",a.G);a.sa=d;a.ya=!0}TBa(a,c.id);var e=UBa(a,c);if(e){d={oc:c,Ct:e.element,EC:!1};var f=VBa(a,d);g.ib(a.B,f,0,d);e.xa(a.C,f);a.Io();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.La(a.JV,d)):(e=1E3*a.context.o.getCurrentTime(),5E3>e&&e>c.startMs&&a.RF(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.La(a.RF,d)),V3(a))}}},XBa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){S3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){T3(a)});
var c=b.data.headerText;g.ve(a.Aa,c);a.T&&a.T.setAttribute("title",c);b.data.eventId&&(a.Z=b.data.eventId);a.ha=g.NH(b.data.trackingParams);a.R=g.NH(b.data.closeTrackingParams);a.K=g.NH(b.data.iconTrackingParams)},TBa=function(a,b){var c=YBa(a,b);
c&&(c==a.o&&(a.o=null),a.A.removeCueRange(c.oc.id),g.ne(c.Ct),g.$a(a.B,c),a.Io(),V3(a))},S3=function(a,b,c,d){if(!a.D){a.ia.show();
a.da=new g.U(function(){g.S(a.context.o.getRootNode(),"ytp-iv-drawer-open")},0);
a.da.start();a.ea=g.HG(a.C,"mousewheel",(0,g.A)(a.bO,a));a.D=!0;a.fa=(0,g.H)();G3(a.context.logger,a.Z,7,void 0,d&&d.oc?d.oc.B:void 0);var e=g.fI();e&&a.ha&&a.R&&p2(e,[a.ha,a.R]);var f={TRIGGER_TYPE:b};(0,g.C)(a.B,function(b){b.EC||(b.EC=!0,D3(a.context.logger,b.oc.B,b.oc.A.NM,f));e&&p2(e,[b.oc.F])});
h2(a.A);c&&(a.H=new g.U(function(){a.ka=a.T;a.sa.focus()},330),a.H.start())}},T3=function(a){a.D&&(a.ia.hide(),g.IG(a.ea),a.ea=null,g.pr(a.context.o.getRootNode(),"ytp-iv-drawer-open"),a.D=!1,h2(a.A),a.H&&a.H.stop(),a.H=new g.U(function(){a.ka&&(a.ka.focus(),a.ka=null)},330),a.H.start())},SBa=function(a){var b=g.Wd("iv-drawer-close-button",a.G);
a.context.A.X(b,"click",a.kK,a);a.context.A.X(a.C,"touchend",function(){a.N.start()});
a.context.A.X(a.C,"scroll",a.wK,a);a.context.B.subscribe("onHideControls",function(){a.aa=!0});
a.context.B.subscribe("onShowControls",function(){a.aa=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.aa=g.nr(a.A.getRootNode(),"ytp-autohide")});
a.L.push(g.aF("iv-button-shown",a.iN,a));a.L.push(g.aF("iv-button-hidden",a.hN,a));a.L.push(g.aF("iv-teaser-shown",a.lN,a));a.L.push(g.aF("iv-teaser-hidden",a.kN,a));a.L.push(g.aF("iv-teaser-clicked",a.jN,a))},UBa=function(a,b){switch(b.type){case "simple":return M3(a.F,b);
case "collaborator":var c=a.F,d={I:"div",ca:["iv-card","iv-card-channel"],P:[{I:"a",ca:["iv-click-target"],U:{href:Z2(b.url),"data-ytid":b.channelId},P:[K3(b.profileImageUrl),{I:"div",M:"iv-card-content",P:[O3(c,b),{I:"h2",M:"iv-card-primary-link",ba:b.title},N3(c,b)]}]}]};d=new g.W(d);L3(c,d,b);return d;case "donation":return c=a.F,d=(0,g.A)(c.F,c,b),M3(c,b,d,d);case "episode":return HBa(a.F,b,"iv-card-episode");case "movie":return HBa(a.F,b,"iv-card-movie");case "playlist":return c=a.F,d={I:"div",
ca:["iv-card","iv-card-playlist"],P:[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.C,{I:"div",M:"iv-card-image-overlay",P:[{I:"span",M:"iv-card-playlist-video-count",ba:b.playlistVideoCount.toString()}]}),{I:"div",M:"iv-card-content",P:[O3(c,b),J3(c,"h2","iv-card-primary-link",b.title),N3(c,b)]}]}]},d=new g.W(d),L3(c,d,b),d;case "poll":return FBa(a.F,b);case "productListing":c=a.F;var e=!g.Wa(b.offers);d=["iv-card"];var f="",k=GBa(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",
e=b.offers[0],k=[],e.price&&k.push({I:"div",M:"iv-card-offer-price",ba:e.price}),e.merchant&&k.push({I:"div",M:"iv-card-offer-merchant",ba:e.merchant}),k={I:"div",P:k});d={I:"div",ca:d,U:{tabindex:"0"},P:[{I:"a",ca:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+b.imageUrl+");",href:Z2(b.url),"aria-hidden":"true",tabindex:"-1"}},{I:"div",M:"iv-card-content",P:[b.sponsored?{I:"div",M:"iv-card-sponsored",P:["Sponsored",{I:"div",M:"iv-ad-info-container",P:[{I:"div",M:"iv-ad-info",
ba:"{{adInfo}}"},{I:"div",M:"iv-ad-info-icon-container",P:[{I:"div",M:"iv-ad-info-icon"},{I:"div",M:"iv-ad-info-callout"}]}]}]}:"",{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[J3(c,"h2",f,b.title),k]}]}]};d=new g.W(d);f=g.he("span");g.ve(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.Mb(f,"adInfo");L3(c,d,b);return d;case "tip":return c=a.F,d=(0,g.A)(c.H,c,b),M3(c,b,d,d);case "video":return c=a.F,d=b.isLiveNow?{I:"span",
ca:["yt-badge","yt-badge-live"],ba:"LIVE NOW"}:"",d={I:"div",ca:["iv-card","iv-card-video"],P:[{I:"a",M:"iv-click-target",U:{href:Z2(b.url)},P:[K3(b.C,b.videoDuration?{I:"span",M:"iv-card-video-duration",ba:b.videoDuration}:""),{I:"div",M:"iv-card-content",P:[O3(c,b),J3(c,"h2","iv-card-primary-link",b.title),N3(c,b),d]}]}]},d=new g.W(d),L3(c,d,b),d}return null},VBa=function(a,b){if(0==a.B.length)return 0;
var c=g.Sa(a.B,function(a){return b.oc.startMs>a.oc.startMs||b.oc.startMs==a.oc.startMs&&b.oc.timestamp>=a.oc.timestamp?!0:!1});
return-1==c?0:c+1},ZBa=function(a){return a.o?"productListing"==a.o.oc.type:(0,g.mj)(a.B,function(a){return"productListing"==a.oc.type})},V3=function(a){g.T(a.A.getRootNode(),"ytp-cards-shopping-active",ZBa(a))},$Ba=function(a,b){if(a.J.A){var c=new m2([0,
a.C.scrollTop],[0,b.Ct.offsetTop],600,Tza);a.context.C.X(c,"animate",function(b){a.C.scrollTop=b.y});
a.context.C.X(c,"finish",function(b){a.C.scrollTop=b.y});
c.play()}else g.pQ(a.J,!0),a.C.scrollTop=b.Ct.offsetTop,g.pQ(a.J,!1)},W3=function(a){return a.o&&a.o.oc?a.o.oc:a.B[0]&&a.B[0].oc?a.B[0].oc:null},YBa=function(a,b){return g.Ra(a.B,function(a){return a.oc.id==b})},X3=function(a,b,c){R3.call(this,a,b);
this.annotation=c;this.isActive=!1},aCa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},Y3=function(a,b,c){X3.call(this,a,b,c);
this.A=null;this.G=!1;this.B=null;this.C=!1;this.H=0;this.o=this.F=this.D=null},Z3=function(a,b,c){X3.call(this,a,b,c);
this.J=this.D=this.K=!1;this.G=5E3;this.C=null;this.H=g.fe("DIV","iv-promo-contents");this.A=this.B=this.o=null;this.F=new g.U(function(){this.o.setAttribute("aria-hidden",!0);g.L(this.B,!1);g.L(this.A,!0)},700,this);
g.K(this,this.F)},bCa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.ra().setAttribute("aria-hidden",!0);a.ra().setAttribute("aria-label","Promotion");a.ra().tabIndex=0;var e=a.annotation.Za(),f=b.image_url;if(f){var k=g.fe("DIV",["iv-promo-img","iv-click-target"]);f=g.fe("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.fe("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.fe("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.fl(k,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}e?(f=g.fe("A","iv-promo-txt"),g.Cd(f,Z2(e)),a.o=f):a.o=g.fe("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.fe("P",null,g.fe("STRONG",null,b.text_line_1));var m=g.fe("P",null,g.fe("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
a.context.D.experiments.o("web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.fe("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.fe("BUTTON",["iv-button","iv-promo-button"],g.fe("SPAN","iv-button-content",f));var p=g.fe("DIV","iv-promo-button-container");p.appendChild(f);e&&a.fl(a.ra(),e,a.annotation.id,b.session_data,a.annotation.o,void 0,c)}g.S(a.o,"iv-click-target");e&&a.fl(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c);break;case "playlist":case "video":l=
g.fe("P",null,g.fe("SPAN",null,b.text_line_1)),m=g.fe("P",null,g.fe("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.fe("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.S(a.o,"iv-click-target"),e&&a.fl(a.o,e,a.annotation.id,b.session_data,a.annotation.o,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);p&&a.H.appendChild(p);c=g.fe("DIV","iv-promo-actions");a.A=g.fe("BUTTON",["iv-promo-expand","ytp-button"]);a.A.title="Expand";a.context.A.X(a.A,
"click",g.La(a.Au,5E3),a);c.appendChild(a.A);g.L(a.A,!1);a.context.A.X(a.ra(),"mouseover",a.vL,a);a.context.A.X(a.ra(),"mouseout",a.uL,a);a.context.A.X(a.ra(),"touchend",g.La(a.Au,5E3),a);a.B=g.fe("BUTTON",["iv-promo-close","ytp-button"]);a.B.title="Close";a.context.A.X(a.B,"click","cta"==a.annotation.style&&b.text_line_3?a.kL:a.AO,a);c.appendChild(a.B);g.or(a.ra(),d);k&&(a.ra().appendChild(k),n&&k.appendChild(n));a.ra().appendChild(a.H);a.ra().appendChild(c)},cCa=function(a){a.D||a.J||a.C||(g.S(a.ra(),
"iv-promo-collapsed"),a.D=!0,a.F.start())},dCa=function(a){a.F.stop();
a.D&&(g.qr(a.ra(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.D=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.L(a.A,!1),g.L(a.B,!0))},eCa=function(a,b){a.C||(a.C=g.Qg(function(){$3(this);
cCa(this)},b,a))},$3=function(a){a.C&&(g.Rg(a.C),a.C=null)},a4=function(a){g.nV.call(this,a);
this.K=!1;this.J=0;this.A={};this.L={};this.kb=new ABa(a);this.G=new g.WG(this);g.K(this,this.G);this.F=this.B=null;this.G.O(this.player,"onVideoAreaChange",(0,g.A)(this.V,this,"onVideoAreaChange"));this.G.O(this.player,"onHideControls",(0,g.A)(this.V,this,"onHideControls"));this.G.O(this.player,"onShowControls",(0,g.A)(this.V,this,"onShowControls"));this.G.O(this.player,"resize",(0,g.A)(this.V,this,"resize"));this.G.O(this.player,"presentingplayerstatechange",(0,g.A)(this.V,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.KR,this);this.subscribe("onShowControls",this.ST,this);this.subscribe("presentingplayerstatechange",this.XS,this);this.subscribe("resize",this.Lw,this);this.subscribe("G",this.HN,this);this.subscribe("F",this.Zh,this);this.subscribe("D",this.sQ,this);this.subscribe("E",this.YQ,this);g.Y(this.player).J.subscribe("vast_info_card_add",this.VE,this);this.T=new g.WG(this);g.K(this,this.T);this.T.O(this.player,g.sR("annotations_module"),this.FN);this.T.O(this.player,
"crx_annotations_module",this.GN);this.N=g.fe("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Z=g.fe("DIV","video-custom-annotations");this.D=new g.W({I:"div",ca:["ytp-player-content","ytp-iv-player-content"]});g.K(this,this.D);g.eV(this.player,this.D.element,4);this.D.hide();this.C=new g.W({I:"div",ca:["ytp-iv-video-content"]});g.K(this,this.C);g.je(this.C.element,g.fe("DIV","video-annotations",this.N,this.Z));this.H=this.o=null;this.R=[];fCa(this)&&this.load();var b=g.he("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Af(this,function(){g.ne(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},gCa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},fCa=function(a){var b=g.Y(a.player);
a=a.player.getVideoData();return 1==(b.mh||a.mh)&&!a.yl||null!==b.J.get(a.videoId)},hCa=function(a,b,c){a.K=!0;
a.F=g.FF(b,c)},iCa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(iCa(a,e))}return c},jCa=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},lCa=function(a,b){var c=kCa(a,b);
if(!c&&"marker"!=b.type)return null;XAa(b,function(a){a=(0,g.A)(this.qU,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new w3(a.ia,b,c);g.K(d,c);return d},mCa=function(a,b){var c=g.fe("DIV",["annotation",
"annotation-type-custom"]);g.L(c,!1);var d=null;switch(b.type){case "branding":if(g.Y(a.player).qd)break;a.D.element.appendChild(c);d=new Y3(c,b4(a),b);break;case "promotion":g.eV(a.player,c,4),d=new Z3(c,b4(a),b)}d&&d.zr();return d},pCa=function(a){var b=a.player.getVideoData();
if(b.se){var c=g.Y(a.player),d=c.J.get(b.videoId);if(d){var e={format:"XML",gd:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.gd.gaming="1");e.Jd=(0,g.A)(function(a,b,c){jCa(this,a,b)||(a=g.qF(c)&&c.responseXML?c.responseXML:null)&&c4(this,a)},a,a.J,b.videoId);
g.xH()&&(e.Jd=nCa(a,e.Jd));e.Sb={ic_only:"1"};oCa(e,d);a.K=!0;g.FF(b.se,e)}}},oCa=function(a,b){a.method="POST";
a.Sb=a.Sb||{};b.Bt&&(a.Sb.ic_coll=b.Bt);b.wi&&(a.Sb.ic_xml=b.wi);b.pl&&(a.Sb.ic_track=b.pl)},qCa=function(a){var b=new g.W({I:"div"});
g.L(b.element,!1);var c=new U3(a.player,b.element,b4(a));g.K(c,b);b.xa(a.D.element);c.zr();return c},b4=function(a){if(!a.H){var b=new g.TG(a);
g.K(a,b);var c=new g.Mn(a);g.K(a,c);a.H=new DBa(b,c,g.Y(a.player),a.player.getVideoData(),a.kb,a.player,a.ia)}return a.H},c4=function(a,b){var c=!1;
rCa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=iCa(a,d[e]),k=null;try{k=UAa(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=mCa(a,k))g.K(a,f),a.L[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.o||(a.o=qCa(a),g.K(a,a.o)),"card"==k.type?WBa(a.o,k):XBa(a.o,k),c=!0;else if(f=lCa(a,k))g.K(a,f),a.A[k.id]=f}}c&&(h2(a.player),a.Lw());g.Kb(a.A,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.A&&
(b=this.A[b.segment.A])&&(a.T=b.annotation)}},a)},rCa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.fI();
if(b){var c=g.eI();c&&g.PH(b,c,[g.NH(a)])}}},tCa=function(a,b,c,d){d?sCa(a,b,c):d4(a,b,c)},d4=function(a,b,c){if(b=a.A[b])x3(b),c&&c.A?(a=(0,g.A)(a.RB,a,b),b.o=new g.U(a,2E3),b.o.start()):a.RB(b)},sCa=function(a,b,c){if(b=a.A[b])x3(b),c&&c.C?(a=(0,g.A)(a.gG,a,b),b.o=new g.U(a,2E3),b.o.start()):a.gG(b)},uCa=function(a,b){var c=a.player.getVideoData();
if(!c.Co)return!1;var d=Z2(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!P3(d))return!1;d=g.vF(d);return d.list||d.p?!1:(d=NBa(b))?c.videoId==d?!0:"new"!=b.target&&g.Y(a.player).o?!0:!1:!1},kCa=function(a,b){if(vCa(b)){var c=b.D||e3(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new r3(b,(0,g.A)(a.N.appendChild,a.N),a.player,a.ia,c)}return null},vCa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in d3)if(a.style==d3[b])return!0;return!1},e4=function(a,b,c,d){a.V(aBa(b,d),c,d)},nCa=function(a,b){return(0,g.A)(function(){if(!this.la()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.La.apply(window,a);this.R.push(g.vH(b))}},a)};
g.MU.prototype.bl=g.ca(13,function(a,b){var c=g.NU(this).C;c&&c.bl(a,b)});
var Iza=/[^\d]+$/,Jza={cm:1,"in":1,mm:1,pc:1,pt:1},Kza={em:1,ex:1};i2.prototype.clone=function(){return new i2(this.start,this.end)};
i2.prototype.getLength=function(){return this.end-this.start};
var j2={},k2=null;g.B(Qza,g.Df);g.B(m2,g.Bu);g.h=m2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.tb())return!1;l2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.Dq();this.Ne("play");-1==this.o&&this.Ne("resume");this.o=1;var b=g.Ka(this);b in j2||(j2[b]=this);Oza();Pza(this,a);return!0};
g.h.stop=function(a){l2(this);this.o=0;a&&(this.progress=1);Rza(this,this.progress);this.Ne("stop");this.Bn()};
g.h.pause=function(){this.tb()&&(l2(this),this.o=-1,this.Ne("pause"))};
g.h.W=function(){0==this.o||this.stop(!1);this.Ne("destroy");m2.ga.W.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Cw=function(){this.Ne("animate")};
g.h.Ne=function(a){this.dispatchEvent(new Qza(a,this))};
g.B(n2,m2);n2.prototype.B=g.z;n2.prototype.Cw=function(){this.B();n2.ga.Cw.call(this)};
n2.prototype.Bn=function(){this.B();n2.ga.Bn.call(this)};
n2.prototype.Dq=function(){this.B();n2.ga.Dq.call(this)};
g.B(o2,n2);o2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.B(s2,g.eg);g.h=s2.prototype;g.h.vu=null;g.h.Fm=null;g.h.ra=function(){return this.Fm};
g.h.addEventListener=function(a,b,c,d){g.Qf(this.Fm,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Zf(this.Fm,a,b,c,d)};
g.h.W=function(){s2.ga.W.call(this);var a=this.Fm;if(a)if(g.Jf(a))a.Oe&&g.Nf(a.Oe);else if(a=g.Tf(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.$f(d[e])&&++b}};g.B(w2,s2);w2.prototype.fill=null;g.B(Xza,s2);x2.prototype.Pf=null;x2.prototype.he=null;x2.prototype.Qn=!0;var Yza=[2,2,6,6,0];g.h=x2.prototype;g.h.clear=function(){this.vb.length=0;this.Qa.length=0;this.Ke.length=0;delete this.Pf;delete this.he;delete this.Qn;return this};
g.h.moveTo=function(a,b){0==g.Pa(this.vb)?this.Ke.length-=2:(this.vb.push(0),this.Qa.push(1));this.Ke.push(a,b);this.he=this.Pf=[a,b];return this};
g.h.Lc=function(a){var b=g.Pa(this.vb);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.vb.push(1),this.Qa.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Ke.push(c,d)}this.Qa[this.Qa.length-1]+=b/2;this.he=[c,d]};
g.h.close=function(){var a=g.Pa(this.vb);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.vb.push(4),this.Qa.push(1),this.he=this.Pf);return this};
g.h.clone=function(){var a=new this.constructor;a.vb=this.vb.concat();a.Qa=this.Qa.concat();a.Ke=this.Ke.concat();a.Pf=this.Pf&&this.Pf.concat();a.he=this.he&&this.he.concat();a.Qn=this.Qn;return a};
g.h.transform=function(a){if(!this.Qn)throw Error("Non-simple path");a.transform(this.Ke,0,this.Ke,0,this.Ke.length/2);this.Pf&&a.transform(this.Pf,0,this.Pf,0,1);this.he&&this.Pf!=this.he&&a.transform(this.he,0,this.he,0,1);return this};
g.h.isEmpty=function(){return 0==this.vb.length};g.B($za,w2);z2.prototype.Ya=function(){return this.A};g.B(A2,g.Zv);A2.prototype.B=null;A2.prototype.Xj=function(){return this.bf?g.ci(this.ra()):g.Ba(this.width)&&g.Ba(this.height)?new g.Od(this.width,this.height):null};
A2.prototype.resume=function(){};g.B(aAa,s2);g.B(u2,Wza);g.B(t2,Wza);g.B(B2,Xza);B2.prototype.clear=function(){g.le(this.ra())};
B2.prototype.setSize=function(a,b){E2(this.ra(),{width:a,height:b})};
g.B(bAa,$za);g.B(C2,aAa);C2.prototype.setSize=function(a,b){E2(this.ra(),{width:a,height:b})};var G2;g.B(D2,A2);var dAa=0;g.h=D2.prototype;g.h.zp=function(){var a=v2(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=v2(this,"g");this.H=v2(this,"defs");this.B=new B2(b,this);a.appendChild(this.H);a.appendChild(b);this.o=a;this.C&&(this.ra().setAttribute("preserveAspectRatio","none"),this.N?this.Pr():this.ra().setAttribute("viewBox","0 0 "+(this.C?this.C+" "+this.R:"")))};
g.h.Pr=function(){if(this.bf){var a=this.Xj();if(0==a.width)this.ra().style.visibility="hidden";else{this.ra().style.visibility="";var b=a.width/this.C;a=a.height/this.R;this.B.ra().setAttribute("transform","scale("+b+" "+a+") translate(0 0)")}}};
g.h.setSize=function(a,b){g.bi(this.ra(),a,b)};
g.h.Xj=function(){if(!g.Mh)return this.bf?g.ci(this.ra()):D2.ga.Xj.call(this);var a=this.width,b=this.height,c=g.u(a)&&-1!=a.indexOf("%"),d=g.u(b)&&-1!=b.indexOf("%");if(!this.bf&&(c||d))return null;if(c){var e=this.ra().parentNode;var f=g.ci(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ra().parentNode,f=f||g.ci(e),b=parseFloat(b)*f.height/100);return new g.Od(a,b)};
g.h.clear=function(){this.B.clear();g.le(this.H);this.A={}};
g.h.drawImage=function(a,b,c,d,e,f){a=v2(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new C2(a,this);(f||this.B).ra().appendChild(e.ra());return e};
g.h.Pj=function(){var a=this.Xj();D2.ga.Pj.call(this);a||this.dispatchEvent("resize");if(this.N){a=this.width;var b=this.height;"string"==typeof a&&-1!=a.indexOf("%")&&"string"==typeof b&&-1!=b.indexOf("%")&&this.K.X(eAa(),"tick",this.Pr);this.Pr()}};
g.h.hm=function(){D2.ga.hm.call(this);this.N&&this.K.La(eAa(),"tick",this.Pr)};
g.h.W=function(){delete this.A;delete this.H;delete this.B;this.K.dispose();delete this.K;D2.ga.W.call(this)};g.r(I2,g.nV);g.h=I2.prototype;
g.h.load=function(){g.nV.prototype.load.call(this);if(!J2(g.Y(this.player).playerStyle)){var a=g.lna(this.player.getVideoData());if(a)a=H2(a,fAa(this)),K2(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.C&&this.C.abort();a={method:"POST",Jd:(0,g.A)(this.xR,this,a),gd:{v:a},withCredentials:!0};"gaming"==g.Y(this.player).playerStyle&&(a.gd.gaming="1");this.R&&(a.gd.ptype="embedded");var c=this.player.getVideoData().SA;c&&(a.Sb={ad_tracking:c});if(b=g.kna(b))if(b=g.gd(b),b=g.dd(b))this.C=
g.FF(b,a)}}};
g.h.unload=function(){K2(this,null);this.C&&(this.C.abort(),this.C=null);g.nV.prototype.unload.call(this)};
g.h.Jc=function(a,b){if(!J2(g.Y(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=H2(b,"new");K2(this,c);return!0}return null};
g.h.getOptions=function(){return J2(g.Y(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.xR=function(a,b){var c=this.C=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=H2(c,fAa(this)))}K2(this,c)};
g.h.XC=function(){if(this.A&&this.A.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<wCa.length;f++){var k=Math.abs(b.width-wCa[f]);if(-1==e||d>=k)e=f,d=k}d=xCa[e];this.B&&g.Kh(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.A.elements.length;++b)if(f=this.A.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.bi(e.element,Math.round(k.width*a.width),f);g.Rh(e.element,m,n);g.qr(e.element,yCa);m=k.left+k.width/2;k=k.top+l/2;g.S(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.qr(e.element,xCa);g.S(e.element,d);(e=g.Ud(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Kh(e,"height",f+"px")}}}}};
g.h.JN=function(a){if(this.A)if("ytp-ce-in-endscreen"==a.getId())this.K=!1,this.A.skip&&1==this.player.getPlayerState()?(g.UU(this.player,!0),this.player.seekTo(Infinity),this.K=!0):(N2(this,this.A.impressionUrls),(a=g.fI())&&g.QH(a,this.A.visualElement));else if(!this.K){a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.S(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.S(b,"ytp-ce-shown");N2(this,c.impressionUrls);(b=g.fI())&&g.QH(b,c.visualElement);
g.Y(this.player).Pb&&this.player.Ba("endscreenelementshown",a)}};
g.h.KN=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.K){a=a.getId().substring(15);var b=this.o[a];g.pr(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.pr(b,"ytp-ce-shown");g.Y(this.player).Pb&&this.player.Ba("endscreenelementhidden",a)}};
g.h.KU=function(a){var b=this;a.target===window&&(new g.U(function(){for(var a in b.o)g.qr(b.o[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.rE=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.nr(c,"ytp-ce-element");){g.nr(c,"subscribe-label")&&O2(this,a);if(g.nr(c,"ytp-ce-channel-subscribe"))return;c=g.se(c)}if(!c||g.nr(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Kw(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Hr?(O2(this,a),this.JF(),this.player.pauseVideo(),c=g.gd(a.targetUrl),c=g.dd(c),g.AV(c,void 0,a.Ld)):(c=this.player.getVideoData().Mc,
c=(0,g.A)(this.SV,this,c,a.targetUrl,a.Ld),c=(0,g.A)(this.JF,this,c),O2(this,a,c))}}};
g.h.SV=function(a,b,c){var d=g.vF(b);a&&d&&(d.v||d.list)?g.L0(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.zV(b,c)};
g.h.Tv=function(a,b){g.nr(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.S(a.element,"ytp-ce-element-hover"):g.Y(this.player).B?(new g.U(function(){g.S(a.element,"ytp-ce-element-hover")},200)).start():g.S(a.element,"ytp-ce-element-hover"),N2(this,b.aM),M2(this,b.id,!0))};
g.h.Kw=function(a,b){g.pr(a.element,"ytp-ce-element-hover");g.pr(a.element,"ytp-ce-force-expand");M2(this,b.id,!1)};
g.h.JF=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var wCa=[346,426,470,506,570,640,853,1280,1920],xCa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),yCa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var qAa={kZ:"current",r1:"new"};var sAa={CLOSE:"close",w1:"openUrl",vJ:"subscribe"},tAa={Js:"click",CLOSE:"close",C_:"hidden",t2:"rollOut",lJ:"rollOver",oJ:"shown"};var wAa={t4:"xx",u4:"xy",A4:"yx",B4:"yy"};g.r(CAa,a3);var IAa={PH:"anchored",f2:"rect",I2:"shapeless"};var NAa={CLOSED:"closed",G1:"playerControlShow",lJ:"rollOver",oJ:"shown"};c3.prototype.Za=function(){var a=WAa(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
c3.prototype.showLinkIcon=function(){return e3(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var d3={PH:"anchored",SH:"branding",CHANNEL:"channel",jZ:"cta",F_:"highlightText",h0:"label",PLAYLIST:"playlist",S1:"popup",W2:"speech",vJ:"subscribe",x3:"title",VIDEO:"video",n4:"website"},SAa={SH:"branding",FY:"card",NZ:"drawer",E_:"highlight",D0:"marker",Y1:"promotion",TEXT:"text",q4:"widget"},TAa={e4:"video_relative",H1:"player_relative"};bBa.prototype.C=function(a,b,c,d){this.o[a]=b?!c:c;a=g.Pb(this.o,function(a){return a});
this.B!=a&&(this.B=a,this.A.V(this.D,a,d))};h3.prototype.ra=function(){return this.D};
h3.prototype.B=function(){};var l3={bevel:1,dropshadow:2};g.r(n3,h3);
n3.prototype.B=function(a,b){var c=g3(a);if(c){var d=b3(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=ZAa(a))&&c.o?c.o:null)&&c.length?c[0]:null){var f=g.Ah(yAa(b,zAa(e,new g.xh(e.H,e.J,e.xl,e.B),b.o))),k=d.clone();c=new g.xh(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.A;k=m3(k,c.effects);l=i3(this,k.width,k.height);m=jBa(c,k.width,k.height,
this.o);d=new g.xh(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.Md(f.x-k.left,f.y-k.top);this.C=17*$2(b.o,e.A,e.o?e.o:"xy");e=c.cornerRadius;f=a.A;var p=this.o&&f3(a),t=p?f.borderWidth+1:f.borderWidth;p=(f=t?new z2(t,p?f.A:f.borderColor):null)?f.Ya()/2:0;t=lBa(d,n);var x=this.F(d,e,n,t),y=n.x;n=n.y;var E=d.width,G=d.height,N=d.left;d=d.top;var O=new x2;O.moveTo(N+e+p,d+p);"t"==t&&(O.Lc(x.start,d+p),O.Lc(y,n),O.Lc(x.end,d+p));O.Lc(N+E-e-p,d+p);y2(O,e,e,-90);"r"==t&&(O.Lc(N+E-p,x.start),
O.Lc(y,n),O.Lc(N+E-p,x.end));O.Lc(N+E-p,d+G-e-p);y2(O,e,e,0);"b"==t&&(O.Lc(x.end,d+G-p),O.Lc(y,n),O.Lc(x.start,d+G-p));O.Lc(N+e+p,d+G-p);y2(O,e,e,90);"l"==t&&(O.Lc(N+p,x.end),O.Lc(y,n),O.Lc(N+p,x.start));O.Lc(N+p,d+e+p);y2(O,e,e,180);O.close();F2(l,O,f,m);if(m=this.ra())g.S(m,"annotation-shape"),g.S(m,"annotation-speech-shape"),g.Rh(m,k.left,k.top),g.bi(m,k.width,k.height),kBa(l,m,c.effects)}}}};
n3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.Gd(c-a/2,d+b,d+e-a-b);return new i2(c,c+a)}
return"t"==d||"b"==d?e(this.C,c.x,a.left,a.width):"l"==d||"r"==d?e(this.C,c.y,a.top,a.height):new i2(0,0)};g.r(o3,h3);o3.prototype.B=function(a,b){var c=g3(a);if(c){var d=b3(c,b);if(!(0>=d.width||0>=d.height)){var e=a.A;c=m3(d,e.effects);var f=i3(this,c.width,c.height),k=new g.xh(0,0,d.width,d.height),l=e.cornerRadius;d=new z2(!e.B&&this.o?1:e.B,e.bgColor);var m=new t2("#000",0),n=d?d.Ya()/2+1:0;k=iBa(k,l,n);F2(f,k,d,m);f=this.ra();g.S(f,"annotation-shape");e=e.o;g.ei(f,this.o?Math.max(e,.9):e);g.Rh(f,c.left,c.top);g.bi(f,c.width,c.height)}}};g.r(p3,h3);
p3.prototype.B=function(a,b){var c=g3(a);if(c){var d=b3(c,b);if(!(0>=d.width||0>=d.height)){c=a.A;var e=m3(d,c.effects),f=i3(this,e.width,e.height),k=new g.xh(0,0,d.width,d.height);d=jBa(c,d.width,d.height,this.o);var l=c.cornerRadius;var m=a.A;var n=this.o&&f3(a),p=n?m.borderWidth+1:m.borderWidth;n=(m=p?new z2(p,n?m.A:m.borderColor):null)?m.Ya()/2+1:0;k=iBa(k,l,n);F2(f,k,m,d);if(k=this.ra())g.S(k,"annotation-shape"),g.S(k,"annotation-popup-shape"),g.Rh(k,e.left,e.top),g.bi(k,e.width,e.height),kBa(f,
k,c.effects)}}};g.r(q3,n3);q3.prototype.F=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new i2(c,c+a)}
return"t"==d||"b"==d?e(this.C,c.x,a.left,a.width):"l"==d||"r"==d?e(this.C,c.y,a.top,a.height):new i2(0,0)};g.r(r3,g.J);g.h=r3.prototype;g.h.gD=function(){this.J||(this.C&&g.L(this.C,!0),this.D&&g.L(this.D,!0),this.B&&(this.B.o=!0,g.ei(this.A,v3(this)?1:0),this.B.B(this.o,t3(this))),this.H.isActive()&&this.H.stop(),this.J=!0,this.K=this.Y.Qh(g.RU(this.F),"mouseleave",function(a){this.Bq.stop();this.Zh(a)}))};
g.h.Zh=function(){this.J&&(this.N?this.H.start():this.SB(),this.B&&(this.B.o=!1,g.ei(this.A,v3(this)?1:0),this.B.B(this.o,t3(this))),this.J=!1,this.K&&(this.Y.La(this.K),this.K=null))};
g.h.SB=function(){this.C&&g.L(this.C,!1);this.D&&g.L(this.D,!1)};
g.h.zO=function(a){this.ea=a;this.Bq.Dm()};
g.h.tL=function(){var a=this.ea,b=new g.Md(a.clientX,a.clientY),c=g.Vh(this.F.getRootNode()),d=pBa(c,this.R);c=(this.D&&g.fi(this.D)||this.C&&g.fi(this.C))&&pBa(c,this.N);d&&d.contains(b)||c&&c.contains(b)?this.gD(a):this.Zh(a)};
g.h.show=function(){var a=this.o.A;a=(a&&0==a.o||"title"==this.o.style||"highlightText"==this.o.style?!1:!0)&&!this.B;var b=!this.A;if(a){var c=t3(this),d=null;"highlight"==this.o.type||"label"==this.o.style?d=new o3:"popup"==this.o.style?d=new p3:"anchored"==this.o.style?d=new n3:"speech"==this.o.style&&(d=new q3);d&&(d.B(this.o,c),this.B=d,c=d.ra())&&(g.L(c,!1),g.S(c,"annotation-type-"+this.o.type.toLowerCase()),this.Z(c))}if(b){c=["annotation"];"highlightText"!=this.o.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.o.type.toLowerCase());this.A=g.fe("DIV",c);g.L(this.A,!1);this.o.C&&(this.G=g.fe("DIV","inner-text"),"label"==this.o.style&&(g.S(this.G,"player-label-text"),this.G.style.backgroundColor=this.o.A.bgColor),g.ve(this.G,this.o.C),this.A.appendChild(this.G));g.RE(this.A,"annotation_id",this.o.id);this.Z(this.A);mBa(this,this.A);if(f3(this.o)&&this.o.showLinkIcon()){if(d=this.o.Za())c=this.A,d=new g.wn(Z2(d)),c.title=d.A+d.B;this.D=g.fe("SPAN","annotation-link-icon");g.L(this.D,
!1);this.A.appendChild(this.D)}nBa(this);f3(this.o)||(this.A.style.cursor="default")}if(a||b){a:{a=this.o.segment.o;if(a.length&&(a=KAa(a[0]))){a=a.D;break a}a=0}this.A&&(this.A.style.zIndex=a);this.B&&this.B.ra()&&(this.B.ra().style.zIndex=a)}g.L(this.A,!0);g.ei(this.A,v3(this)?1:0);u3(this);this.B&&this.B.ra()&&g.L(this.B.ra(),!0)};
g.h.hide=function(){this.A&&g.L(this.A,!1);this.B&&this.B.ra()&&g.L(this.B.ra(),!1);this.L&&(this.Y.La(this.L),this.L=null)};g.r(w3,g.J);g.h=w3.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(rBa(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.A.subscribe("resize",this.fD,this),this.A.subscribe("onVideoAreaChange",this.WE,this))};
g.h.destroy=function(){if(this.view){rBa(this);var a=this.view;g.UG(a.Y);a.Bq.dispose();a.H.dispose();a.A&&g.ne(a.A);a.B&&a.B.ra()&&g.ne(a.B.ra())}x3(this)};
g.h.WE=function(){u3(this.view)};
g.h.fD=function(){u3(this.view)};g.r(sBa,r2);g.r(y3,r2);g.r(tBa,y3);g.r(uBa,r2);g.r(vBa,r2);g.r(xBa,y3);g.r(yBa,y3);g.r(zBa,r2);g.r(z3,r2);I3.prototype.B=function(a,b){var c=g.Be(b.target,"label");c&&g.T(c,"iv-card-poll-choice-focused",a)};
I3.prototype.G=function(a,b){var c=g.Ce(b.target,"iv-card-poll");if(c)if(a.C)g.Wd("iv-card-sign-in-button",c).click();else{var d=parseInt(Mza(b.target),10);if(null==a.o)a.choices[d].count++,a.o=d;else if(a.o!=d){var e=a.choices[a.o];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.o=d}else e=a.choices[a.o],e.count=Math.max(e.count-1,0),a.o=null;EBa(a,c);g.JF(this.o.videoData.se,{gd:{action_poll_vote:1},Sb:{poll_id:a.id,index:d,session_token:a.J}});E3(this.o.logger,a.B,void 0,{"link-id":d},a.A.click,
5);(c=g.fI())&&g.RH(c,a.F)}};
I3.prototype.F=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.J,a.G)});
IBa(this,a,!0,c)};
I3.prototype.H=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.La(b,a.R,a.J,a.G));IBa(this,a,!1,b)};g.r(R3,g.J);g.h=R3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.qR(a,b,{id:c});g.K(this,a);a.namespace="annotations_module";d&&Hza(a).subscribe("onEnter",d,this);e&&Hza(a).subscribe("onExit",e,this);g.$U(this.context.o,[a])};
g.h.zr=function(){this.context.B.subscribe("resize",this.Io,this)};
g.h.ra=function(){return this.Ea};
g.h.fl=function(a,b,c,d,e,f,k){this.context.A.X(a,"click",g.La(this.Yp,b,c,d,e,f||[],k||0),this);this.context.A.X(a,"touchstart",g.La(function(){this.my=!1}),this);
this.context.A.X(a,"touchmove",g.La(function(){this.my=!0}),this)};
g.h.Yp=function(a,b,c,d,e,f,k){if(this.my)return!1;k&&(k.stopPropagation(),k.preventDefault());QBa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.fa=(0,g.H)()};
g.h.hide=function(){};
g.h.destroy=function(){g.ne(this.ra())};
g.h.Io=function(){};g.r(U3,R3);g.h=U3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.B.length)(a=this.A.getRootNode())?(a=g.ci(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Io=function(){var a=this.isAvailable();g.L(this.ra(),a);g.T(this.context.o.getRootNode(),"ytp-iv-drawer-enabled",a);h2(this.A)};
g.h.destroy=function(){this.A.bl(!1);this.A.getRootNode().removeChild(this.G);g.bF(this.L);g.IG(this.ea);this.da&&this.da.dispose();this.H&&this.H.dispose();R3.prototype.destroy.call(this)};
g.h.bO=function(a){this.N.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.C.scrollTop+=a};
g.h.RF=function(a){if(!g.nr(this.A.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.fI(),c=this.o?this.o.oc.D:this.K;b&&c&&q2(b,[c]);this.o=a;V3(this)}g.fi(this.ra())&&(2==this.context.o.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.o.getAdState():void 0):(b=isNaN(void 0)?this.context.o.getPlayerState():void 0,b=1==b||0==b&&0===this.context.o.getCurrentTime()),b&&a.oc.teaserDurationMs&&this.A.bl(!0,{teaserText:a.oc.teaserText,durationMs:a.oc.teaserDurationMs}));this.ma.isActive()||
((!this.D||!this.N.isActive()&&this.aa)&&$Ba(this,a),this.ma.start(910+a.oc.teaserDurationMs))}};
g.h.JV=function(a){this.D||(this.o=a,V3(this),$Ba(this,a),S3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.kK=function(){if(this.D){G3(this.context.logger,this.Z,4,W3(this).A.close);var a=g.fI();a&&this.R&&g.RH(a,this.R);T3(this)}};
g.h.wK=function(){g.T(this.G,"iv-drawer-scrolled",0<this.C.scrollTop)};
g.h.iN=function(){var a=g.fI(),b=W3(this);b=b?b.D:this.K;a&&b&&p2(a,[b])};
g.h.hN=function(){var a=g.fI(),b=W3(this);b=b?b.D:this.K;a&&b&&q2(a,[b])};
g.h.lN=function(){var a=W3(this);H3(this.context.logger,8,a.B,a.A.bW);var b=g.fI();b&&a&&p2(b,[a.H,a.D])};
g.h.kN=function(){var a=g.fI(),b=W3(this);a&&b&&q2(a,[b.H])};
g.h.jN=function(a){var b=W3(this),c=g.fI();this.o?a?(a=this.context.logger,H3(a,9,b.B,b.A.Kx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.RH(c,b.H)):(a=this.context.logger,H3(a,12,b.B,b.A.Kx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&g.RH(c,b.D)):(a=this.context.logger,G3(a,this.Z,12,b.A.Kx),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.K&&g.RH(c,this.K))};
var RBa={collaborator:sBa,donation:tBa,episode:z3,movie:z3,playlist:uBa,poll:vBa,productListing:xBa,simple:y3,tip:yBa,video:zBa};g.r(X3,R3);X3.prototype.zr=function(){R3.prototype.zr.call(this);aCa(this)};
X3.prototype.show=function(){R3.prototype.show.call(this);var a=g.fI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&p2(a,[g.NH(b.itct)])};
X3.prototype.hide=function(){R3.prototype.hide.call(this);var a=g.fI(),b=this.annotation.data;a&&b&&(b=b.session_data)&&q2(a,[g.NH(b.itct)])};g.r(Y3,X3);g.h=Y3.prototype;g.h.TV=function(a,b,c,d){this.B.stop();if(!this.C){var e=g.ci(a);this.o||(g.ai(a,e.width),g.ai(b,e.width));g.Kh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.Kh(c,"right","1px");this.C=!0;g.L(a,!0);this.D=new g.U(function(){g.S(this.ra(),"iv-branding-active")},0,this);
this.D.start()}};
g.h.YL=function(a,b){g.pr(this.ra(),"iv-branding-active");this.F=new g.U((0,g.A)(function(){g.L(a,!1);this.o||g.ai(b,0)},this),250);
this.F.start();this.C=!1};
g.h.show=function(){if(!this.isActive){X3.prototype.show.call(this);if(!this.G){g.S(this.ra(),"iv-branding");var a=this.annotation.data;this.H=a.image_width;this.A=g.fe("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.L(this.A,!1);var b=g.fe("DIV","branding-img-container",this.A);this.ra().appendChild(b);var c=g.fe("DIV","iv-branding-context-name");g.ve(c,a.channel_name);var d=g.fe("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=
new g.x_(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.o),this.o.xa(d);b=g.fe("DIV","iv-branding-context-subscribe-caret");c=g.fe("DIV","branding-context-container-inner",b,c,d);g.L(c,!1);d=g.fe("DIV","branding-context-container-outer",c);g.Kh(d,"right",this.H+"px");this.ra().appendChild(d);var e=this.annotation.Za();e&&this.fl(this.A,e,this.annotation.id,a.session_data,
this.annotation.o);this.B=new g.U(g.La(this.YL,c,d),500,this);g.K(this,this.B);this.context.A.X(this.ra(),"mouseover",(0,g.A)(this.TV,this,c,d,b,a.image_height));this.context.A.X(this.ra(),"mouseout",(0,g.A)(this.B.start,this.B,void 0));this.G=!0}D3(this.context.logger,this.annotation.o);g.L(this.ra(),!0);this.isActive=!0;if(this.A){a=this.A;var f=void 0===f?0:f;b=g.di(a).width;c=g.Ba(void 0)?void 0:b;g.Rh(a,c);f=new o2(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,Sza);g.K(this,f);this.context.C.X(f,
"begin",g.La(g.L,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(X3.prototype.hide.call(this),g.L(this.ra(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);X3.prototype.destroy.call(this)};g.r(Z3,X3);g.h=Z3.prototype;g.h.show=function(){this.isActive||(X3.prototype.show.call(this),this.K||(bCa(this),this.K=!0),g.L(this.ra(),!0),this.annotation&&this.annotation.o&&D3(this.context.logger,this.annotation.o),g.Qg(function(){g.pr(this.ra(),"iv-promo-inactive")},100,this),this.ra().removeAttribute("aria-hidden"),this.isActive=!0,$3(this),dCa(this),eCa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.S(this.ra(),"iv-promo-inactive"),this.isActive=!1,this.ra().setAttribute("aria-hidden",!0))};
g.h.Yp=function(a,b,c,d,e,f,k){return this.D?!1:X3.prototype.Yp.call(this,a,b,c,d,e,f,k)};
g.h.Au=function(a,b){b.stopPropagation();dCa(this);eCa(this,a);this.o.focus()};
g.h.vL=function(a){this.J=!0;this.Au(500,a)};
g.h.uL=function(){this.J=!1;cCa(this)};
g.h.AO=function(a){a.stopPropagation();this.hide();F3(this.context.logger,this.annotation.o)};
g.h.kL=function(a){a.stopPropagation();$3(this);this.D=!0;g.S(this.ra(),"iv-promo-collapsed-no-delay");this.F.start();F3(this.context.logger,this.annotation.o)};
g.h.destroy=function(){this.F.dispose();X3.prototype.destroy.call(this)};g.r(a4,g.nV);g.h=a4.prototype;g.h.Jc=function(a,b){if(!gCa(g.Y(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.$s(b);c&&c4(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(TBa(this.o,b),h2(this.player)),!0}return null};
g.h.getOptions=function(){return gCa(g.Y(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Lw=function(){if(this.C){var a=g.RU(this.player).getVideoContentRect(!0);g.bi(this.C.element,a.width,a.height);g.Rh(this.C.element,a.left,a.top)}if(this.o){var b=g.YU(this.player);a=this.o;b=b.width;g.T(a.G,"iv-drawer-small",426>=b);g.T(a.G,"iv-drawer-big",1280<=b)}};
g.h.XS=function(a){this.Qc(a.state);g.X(a.state,2)&&(this.ee()&&this.te()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.bl(!1))};
g.h.load=function(){g.nV.prototype.load.call(this);this.Qc(g.QU(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.A)(this.BR,this,b,this.J),d=(0,g.A)(function(){this.F=null},this);
g.xH()&&(c=nCa(this,c));c={format:"XML",Jd:c,onError:d,gd:{}};a.isPharma&&(c.gd.pharma="1");c.method="POST";c.withCredentials=!0;d=g.Y(this.player);"gaming"==d.playerStyle&&(c.gd.gaming="1");(b=d.J.get(b))&&oCa(c,b);b=b&&(b.wi||b.Bt);if(!a.Bo||b)a.se?hCa(this,a.se,c):(this.B=(0,g.A)(this.IN,this,c),this.player.addEventListener("videodatachange",this.B));g.eV(this.player,this.C.element,4);this.Lw()};
g.h.Qc=function(a){a=!a.isCued()&&!g.X(a,1024);g.pQ(this.D,a);g.pQ(this.C,a)};
g.h.IN=function(a){var b=this.player.getVideoData();b.se&&(this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null),hCa(this,b.se,a))};
g.h.unload=function(){BBa(this.kb);g.cV(this.player,"annotations_module");g.Kb(this.A,function(a){a.destroy()});
g.Kb(this.L,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,h2(this.player));this.K=!1;this.F&&(this.F.abort(),this.F=null);this.A={};this.L={};this.D.hide();g.nV.prototype.unload.call(this);g.oQ(this.C);this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.h.BR=function(a,b,c){this.F=null;if(!jCa(this,b,a)&&(a=g.qF(c)&&c.responseXML?c.responseXML:null)){c4(this,a);g.S(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.A){b=this.A[d].annotation;if(b.segment)if(c=b.segment,c.o.length)if(c=c.o[0].A||c.o[0].o||c.o[0].B,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.C,f.visible=!0);b=new g.qR(c,e,f);a.push(b)}}g.$U(this.player,a)}};
g.h.VE=function(a){a==this.player.getVideoData().videoId&&(this.loaded?pCa(this):this.load())};
g.h.FN=function(a){a=a.getId();var b=this.A[a];b&&!b.B&&(b=b.annotation,sCa(this,a),D3(this.kb,b.o))};
g.h.GN=function(a){d4(this,a.getId())};
g.h.RB=function(a){a&&(a.hide(),e4(this,"shown",!1,a.annotation.id),this.Zo(a.annotation,"hidden"))};
g.h.gG=function(a){a&&(a.show(),e4(this,"shown",!0,a.annotation.id),this.Zo(a.annotation,"shown"))};
g.h.qU=function(a,b,c){var d=this.A[a];if(d&&b.value!=c){b.value=c;var e=!1;XAa(d.annotation,function(a){e=e||a.value});
tCa(this,a,b,e)}};
g.h.sQ=function(a){if(a&&a.id){var b=a.Za();if(b){var c=Z2(b);if(c){var d=(0,g.A)(this.Zo,this,a,"click");if("new"==Q3(c,b.target)||uCa(this,b))d(),d=null;E3(this.kb,a.o,d)}}}};
g.h.Zo=function(a,b){VAa(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!uCa(this,c.url))){e=NBa(c.url);var f=MBa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=b4(this).o,g.L0(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&b4(this).o.Nc()&&b4(this).o.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.Y(this.player),(d=Z2(c.url))?(f=LBa(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.La(OBa,e.pageId,e.Wc),d=new g.wn(d),g.An(d,e(d.B)),d=d.toString())):
d=null,d&&(this.player.pauseVideo(),c=Q3(d,c.url.target),e=a.itct,"ei"in g.vF(d)&&(d=g.qh(d,"ei")),g.AV(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.KR=function(){e4(this,"playerControlShow",!1)};
g.h.ST=function(){e4(this,"playerControlShow",!0)};
g.h.HN=function(a){e4(this,"rollOver",!0,a.id)};
g.h.Zh=function(a){e4(this,"rollOver",!1,a.id)};
g.h.YQ=function(a){a&&a.id&&(this.A[a.id].B=!0,d4(this,a.id),F3(this.kb,a.o),this.Zo(a,"close"),e4(this,"closed",!0,a.id))};
g.h.ee=function(){return!!this.o&&this.o.isAvailable()};
g.h.te=function(){this.ee();return!!this.o&&this.o.D};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.ee();this.o&&(a?c?S3(this.o,c,b):S3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):T3(this.o))};
g.h.bl=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.W=function(){g.Y(this.player).J.unsubscribe("vast_info_card_add",this.VE,this);g.pr(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.R,b=0,c=a.length;b<c;b++)g.yH(a[b]);this.R.length=0;g.nV.prototype.W.call(this)};g.VZ.annotations_module=a4;g.VZ.creatorendscreen=I2;})(_yt_player);
